### ISSUE TITLE
ingress with simple routes periodically 404ing

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1038]
User report:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-users/EseVUYqQA2o/Gqw4XG_-AQAJ

cc @costinm @andraxylia

**Comment by ldemailly** [comment]
for 404 vs 503: https://github.com/envoyproxy/envoy/issues/1820

for 404 itself matt kindly pointed me at https://envoyproxy.github.io/envoy/configuration/http_conn_man/route_config/route_config.html#config-http-conn-man-route-table
and "validate_clusters" - I want to add a test first and then see if indeed that fixes it

**Comment by ldemailly** [comment]
I have it reproduced in https://github.com/istio/istio/pull/1041

**Comment by kdillane** [comment]
What is the on-going story here?  How close is the team to identifying a root cause?  We can help however possible to help isolate the issue.

We have begun running some performance tests against applications running in our cluster, but are seeing a stream of 404s, up to 50% of requests at 450tps.  During these tests, we have enabled Horizontal Pod Autoscaling. 

When we disable Horizonte Pod Autoscaling (locking in at 1 Pod), we saw very different results.  While the error rate was still non-0 these were likely not caused by the same 404 issue.

Initially we saw a mixture of 404s and 50*s.  When we enabled liveness and readiness probes, the 50* status codes reduced significantly.

**Comment by kyessenov** [comment]
We know the root cause of this behavior. There are on-going efforts:
1. The next generation of the Envoy configuration protocol should fix this fundamentally. You can read more about this [here](https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md). Unfortunately, this won't be ready soon since there's a lot of plumbing to do in both envoy and management plane.

2. There're other efforts to enable probes and solve 404 using them in the shorter term. I'm not involved in that, @andraxylia or @costinm could probably elaborate.

**Comment by ldemailly** [comment]
there is also a test reproducing the issue https://github.com/istio/istio/pull/1041

**Comment by kdillane** [comment]
Are there expected timelines for both 1 and 2?  At this point we're trying to understand if using Istio is a viable solution.

Would downgrading to 0.1.6 solve the problem?

**Comment by kdillane** [comment]
Just a follow-up: we have run another test with 5 Pods, but no Horizonte Pod Autoscaler.  For around 5 minutes we saw the consistent 404s, but eventually hit a steady state of 450tps spread across the 5 Pods.  This problem down not appear to be related to throughput though.

**Comment by kdillane** [comment]
Bump, hoping to get an answer to the questions I posted.  We are super excited about using Istio, but want to make sure it's possible to use it without triggering (or working around) the 404s.  It sounds like this issue surfaces when Envoy configuration changes which would be cause by route-rule updates or when the state of individual Pods changes behind a Service (both very common and potentially uncontrollable cases).

Is this only affecting the 0.2 release of Istio?  Has anyone invested effort to determine if 0.1.6 is affected?

**Comment by andraxylia** [comment]
Are you affected by the Ingress on startup or by the route rule config update? What is your timeline?

For 2), we are working on a few things, tentative is end of December (release 0.4):

Envoy will be fixed to return 503 instead of 404 for routing rules change envoy/envoyproxy#data-plane-api/246. We also investigate configuring an empty cluster.

For Ingress short term we are looking at a combination of readiness probes + snapshot of config on disk to deal with envoy restart by pilot agent.

We have not investigated 0.1.6, but it likely does not have the 404 on route-rule changes, because the 404 is caused by introduction of Envoy LDS API in 0.2.

**Comment by kdillane** [comment]
>>Are you affected by the Ingress on startup or by the route rule config update?
We seem to be affected upon scaling of a Deployment (typically quickly up or down).  We can test a routing rule change, but haven't specifically tested that.

>>Envoy will be fixed to return 503 instead of 404 for routing rules change envoy/envoyproxy#data-plane-api/246. We also investigate configuring an empty cluster.
What is the behavior this is fixing in terms of Istio?

>>For Ingress short term we are looking at a combination of readiness probes + snapshot of config on disk to deal with envoy restart by pilot agent.
Is this the fix that will be provided by end of December?

**Comment by andraxylia** [comment]
Thanks for clarifying the trigger to be the scaling of the Deployment. We need to root cause this separately from the routing rules change. Can you please post your relevant routing rules & ingress config? What is you overall scale in terms of number of pods and services, and how many pods / service do you have in the beginning and at the end? 

For Envoy fix: This is making Istio return 503 instead of 404 when the RDS response refers to clusters that do not exist. Because the RDS and CDS APIs are called separately, in any order, RDS response may arrive before CDS. Longer term, the fix will be to use the new ADS Envoy v2 API  (Aggregated Discovery service), that does not have this problem.

We hope to get a new Envoy build containing the above fix before end of Dec + rest of the fixes (readiness probes etc ). The release cadence is every month, if it is not Dec it will be Jan.

**Comment by kdillane** [comment]
I've attached a repro case using an echo container image.
[repro.yaml.zip](https://github.com/istio/istio/files/1512193/repro.yaml.zip)

**Comment by mclarke47** [comment]
Is this still being targeted for 0.3.x?

**Comment by kdillane** [comment]
For the repro case I provided, it looks like this may have been in part caused by a bug in Kubernetes (https://github.com/kubernetes/kubernetes/pull/53690).  With Horizontal Pod Autoscaling enabled, it was possible for the desired number of replicas to exceed the max number, causing the number of replicas to jump up and down.  This did help us to uncover the issue with route change propagation, but the specific repro should stop working as of Kubernetes 1.9.

**Comment by kdillane** [comment]
Is there some way to follow progress on the effort to address/solve this Issue?

**Comment by ldemailly** [comment]
cc @jasminejaksic

**Comment by andraxylia** [comment]
@kdillane this is targeted for 0.6 release in February.

**Comment by kdillane** [comment]
That seems fair.  My question was more around understanding how to track the incremental effort of an open Issue.  Milestones can change, that is just how projects run.  However, we are trying to understand how to follow what is changing in Istio to address this Issue and how to understand the progress along that path to completion.

**Comment by ldemailly** [comment]
related to #3295

**Comment by ldemailly** [comment]
I think another source of 503s is https://github.com/istio/istio/pull/4145#issuecomment-372000185
ie us putting pods in service before they are ready (pending instead of running)

**Comment by brant4test** [comment]
hi, team, how's #1038 going? Is this solved? Thanks!

**Comment by ldemailly** [comment]
It's still being worked on, it's still expected to come with an envoy and pilot changes for 0.7
(which we will delay by a couple of days to catch the envoy fix)

**Comment by kdillane** [comment]
Is this still slated for 0.7.0 release?

**Comment by kdillane** [comment]
Bump?  Has this been release as part of 0.7.1?

**Comment by ldemailly** [comment]
Some qualitative improvements happened (ie fewer 503s) in 0.7.1 but there are still 503s in some cases and it will be a major focus again once the envoy v2 and istio v1alpha3 API changes are made in 0.8

**Comment by ldemailly** [comment]
the test is now in master, just need to drop the t.Skip() when we have a fix

**Comment by sakshigoel12** [comment]
@ldemailly what is pending to close this issue?

**Comment by ldemailly** [comment]
fixing 503s is still pending

**Comment by rshriram** [comment]
@sakshigoel12 we have ingress gateway tests for the 503 and they were passing, until we had to disable the test due to mixer filter enablement. 
I think @ldemailly wants somebody else to port his old PoC test to use the new networking APIs. I would focus more on re-enabling the existing tests.

**Comment by ldemailly** [comment]
Afaik we still have 503s and the newer tests only passed some times because they aren't deterministic was my understanding - in other words, a customer making changes will see 503s when they shouldn't is still the status afaik - @andraxylia knows more details.

**Comment by ldemailly** [comment]
@sakshigoel12 any reason you removed the 1.0 label ? do we really think it's ok for istio to generate spurious errors ?

**Comment by rshriram** [comment]
Please produce a repeatable test to show 503s are still occurring with the gateways, when updating virtual services/destination rules in the "prescribed" manner (add subsets to destination rules, then add weights to virtual services. Remove weights from virtual services than remove subsets from destination rules).

**Comment by andraxylia** [comment]
I will take care of this.

**Comment by sakshigoel12** [comment]
We are using milestone (and pipeline) vs label to indicate 1.0  requirements. It is setup correctly.

**Comment by ldemailly** [comment]
yes, thanks, nevermind, it looks like the label is completely deleted / I didn't know

**Comment by louiscryan** [comment]
@andraxylia can you provide an update here on the current known state. Is this bug too broad at this point?

**Comment by andraxylia** [comment]
@louiscryan we have a test for this but I wanted to do some more manual tests before we claim it is fixed. The bug is not too broad, it covers the scenarios of route rule changes.

**Comment by jasmine-jaksic** [comment]
@andraxylia Can you please test it manually with 0.8 and confirm whether this still exists?

**Comment by andraxylia** [comment]
There are still some issues with 0.8 image, though not in all scenarios. I tried with bookinfo app, changing the VirtualService as below produces traffic loss.

istioctl replace -f samples/bookinfo/routing/route-rule-reviews-80-20.yaml 

to 

istioctl replace -f samples/bookinfo/routing/route-rule-all-v1.yaml 


This can be easily reproduced by installing booking, running fortio continuosly from the laptop, and playing with the existing traffic routing rules defined in samples/bookinfo/routing/route-rule*. The fortio command is:

fortio load -loglevel warning -c 1 -qps 8 -t 0 <GW_IP>/productpage

This is the error message:
15:04:32 W http_client.go:581> Parsed non ok code 503 (HTTP/1.1 503)

I will try with a latest image that has RDS.

**Comment by jasmine-jaksic** [comment]
@douglas-reid Per our discussion, please verify that the 503 scenario you encountered is still reproducible. If not, let's close this issue tomorrow.

**Comment by andraxylia** [comment]
As discussed with @douglas-reid , he was seeing 503s with stable traffic , which is covered by #3295, and with a qps of 20s.

**Comment by ldemailly** [comment]
but that other issue is also claimed to be fixed, so what is the explanation for what doug observed?

**Comment by andraxylia** [comment]
It's the bookinfo not handling well concurrent requests. If I run fortio with qps 20 and 4 concurrent threads, I see some 503s from time to time, but if I run it with 1 thread and 100 qps there is no 503.

fortio load -loglevel warning -c 1 -qps 20 -t 0 35.232.86.12/productpage

@costinm ran 1000 qps with fortio on the backends, for about a month, without seeing any 503s. I saw the stress test dashboard with 100% success.

**Comment by jasmine-jaksic** [comment]
Added #6826 for documenting the known issue

**Comment by ldemailly** [comment]
are you saying you see 503s with bookinfo without istio?
