### ISSUE TITLE
Istio Virtual Service with Ingress Gateway is Reporting 403 with RBAC Authorization

### ISSUE THREAD

**Issue by krishnadurai** [istio/istio#14885]
**Bug description**

I've followed Authorization [guide](https://istio.io/docs/tasks/security/rbac-groups/) to setup RBAC policies to httpbin service.
Additionally, I've gone on to test this setup for requests through ingress gateway by applying the below configuration. I get a `403` based on the below config when I try to hit the API from the internet with  
`curl --header "Authorization: Bearer $TOKEN" -I -HHost:httpbin.rbac-groups-test-ns.svc.cluster.local $INGRESS_HOST:$INGRESS_PORT/status/200 -s -o /dev/null -w "%{http_code}\n"`. 
Though when I try hitting the httpbin API through the sleep pod within the same namespace, it works with a `200` response.
`kubectl exec $(kubectl get pod -l app=sleep -n $NS -o jsonpath={.items..metadata.name}) -c sleep -n $NS -- curl http://httpbin.$NS:8000/status/200 -s -o /dev/null -w "%{http_code}\n" --header "Authorization: Bearer $TOKEN"`

Configurations:
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["default", "rbac-groups-test-ns"]
```
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: httpbin-viewer
  namespace: rbac-groups-test-ns
spec:
  rules:
  - services: ["httpbin.rbac-groups-test-ns.svc.cluster.local"]
    methods: ["GET"]
```
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-httpbin-viewer
  namespace: rbac-groups-test-ns
spec:
  subjects:
  - group: "group1"
  - properties:
      source.namespace: "istio-system"
  - properties:
      source.namespace: "rbac-groups-test-ns"

  roleRef:
    kind: ServiceRole
    name: "httpbin-viewer"
```

```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: httpbin
    namespace: rbac-groups-test-ns
  spec:
    gateways:
    - httpbin-gateway
    hosts:
    - httpbin.rbac-groups-test-ns.svc.cluster.local
    http:
    - match:
      - uri:
          prefix: /status
      - uri:
          prefix: /delay
      route:
      - destination:
          host: httpbin
          port:
            number: 8000
```
```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: httpbin-gateway
    namespace: rbac-groups-test-ns
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - httpbin.rbac-groups-test-ns.svc.cluster.local
      port:
        name: http
        number: 80
        protocol: HTTP
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
Should receive a 200 when accessed from the internet.
curl --header "Authorization: Bearer $TOKEN" -I -HHost:httpbin.rbac-groups-test-ns.svc.cluster.local $INGRESS_HOST:$INGRESS_PORT/status/200 -s -o /dev/null -w "%{http_code}\n"`
 
**Steps to reproduce the bug**
Described above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`istioctl version --remote`
```
client version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"brew", Host:"Mojave.local", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.8"}
citadel version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
galley version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
ingressgateway version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
pilot version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
policy version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
sidecar-injector version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
telemetry version: version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
```
   
`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.6", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-05-18T01:21:01Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Using Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by yangminzhu** [comment]
Do you mean you receive 403 when accessing through ingress gateway with the following command?
```
curl --header "Authorization: Bearer $TOKEN" -I -HHost:httpbin.rbac-groups-test-ns.svc.cluster.local $INGRESS_HOST:$INGRESS_PORT/status/200 -s -o /dev/null -w "%{http_code}\n"
```

It seems the ingress gateway doesn't forward the `Authorization` header to the httpbin service which caused the 403 rejection from the httpbin service.

We'll add native RBAC support to ingress gateway which allows you to specify a ServiceRole on the ingress gateway directly. The code is added in 1.2 but we're still evaluating the API so didn't add any documentation for it, it will likely be released in 1.3.

For now, you could copy the value of the `Authorization` header in the istio ingress gateway so that the `httpbin` service could find and validate it. But it seems the current virtual service doesn't support to copy an existing header: https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#Headers-HeaderOperations, @costinm @howardjohn to confirm

So one workaround is you could write a custom Lua filter using EnvoyConfig on ingress gateway to copy the `Authorization` header manually.

**Comment by krishnadurai** [comment]
@yangminzhu Yes, this is what I was looking for!

Then this might mean the request is still authenticated though still not authorized? I thought the JWT would contain the Authentication information too. If it is not passed on, then it should result in a 401, shouldn't it? Please correct my understanding if I'm wrong.

I'll wait for @costinm and @howardjohn to confirm.

**Comment by yangminzhu** [comment]
@krishnadurai Would you mind to share your authentication policy? It's possible to pass the authentication (i.e. no 401) but rejected by authorization (i.e. 403) if you set `origin_is_optional` to true: https://github.com/istio/api/blob/868f99fbab121c68c0877878c71926b7bde8b6ea/authentication/v1alpha1/policy.proto#L356

**Comment by krishnadurai** [comment]
@yangminzhu Here is my authentication policy:
```
apiVersion: v1
items:
- apiVersion: authentication.istio.io/v1alpha1
  kind: Policy
  metadata:
    name: jwt-example
    namespace: default
  spec:
    origins:
    - jwt:
        issuer: testing@secure.istio.io
        jwksUri: https://raw.githubusercontent.com/istio/istio/release-1.1/security/tools/jwt/samples/jwks.json
    principalBinding: USE_ORIGIN
    targets:
    - name: httpbin
kind: List
```

**Comment by krishnadurai** [comment]
@yangminzhu could you please confirm if the 1.2 Istio release supports RBAC authorization on ingress requests from outside the Kubernetes cluster?
I've debugged this example and the filter appears to be right after debugging.

**Comment by yangminzhu** [comment]
@krishnadurai The code is added in 1.2 to support RBAC authorization on ingress **gateway**, you could use it but we haven't announced the feature publicly on istio.io as we need some more time to test and update the documentation, we'll likely announce it in 1.3.

**Comment by aerotog** [comment]
I believe the RBAC Gateway hidden feature is the root cause of a problem we encountered this week when upgrading from Istio 1.1.9 to 1.2.3. After upgrading, we were getting RBAC 403 responses whenever using our Ingress Gateways. After some testing, we fixed the problem by disabling RBAC for Istio's namespace (istio-system by convention).

We have RBAC configured with EXCLUSION and its on by default for all namespaces. This worked fine in Istio 1.1, but b/c of the hidden RBAC Gateway feature, we have to explicitly exclude the Istio namespace for the Gateways to work the way they did in Istio 1.1.

I don't know if this new requirement is documented anywhere, but I think it would be helpful to include this in the upgrade instructions for Istio 1.2. Especially since the RBAC enabled Gateway feature isn't advertised in 1.2.

**Comment by Jeffwan** [comment]
@yangminzhu 

> It seems the ingress gateway doesn't forward the Authorization header to the httpbin service which caused the 403 rejection from the httpbin service.

Could I know if that's still true? I have the similar issue in istio 1.1.3. 

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ingressgateway-jwt-policy
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 80
  origins:
  - jwt:
      issuer: "https://validate_website/xxxx"
      jwksUri: "https://validate_website/xxxx/.well-known/jwks.json"
  principalBinding: USE_ORIGIN
```

Authentication works well but seems Authorization header didn't get passed into service, 

Here's the debug info on istio-proxy pod of service.
```
, dynamicMetadata: filter_metadata {
  key: "istio_authn"
  value {
  }
}

[2019-09-24 06:02:32.032][67][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:114] enforced denied
```

If I change to namespace level policy, it's working perfectly. My case need fine grain control and I'd like to use namespace RBAC rather than Gateway level. But I don't like to create every single policy for different namespaces, that's the reason I create a global one on `istio-ingressgateway`. Do you have any ideas?

**Comment by yangminzhu** [comment]
> I believe the RBAC Gateway hidden feature is the root cause of a problem we encountered this week when upgrading from Istio 1.1.9 to 1.2.3. After upgrading, we were getting RBAC 403 responses whenever using our Ingress Gateways. After some testing, we fixed the problem by disabling RBAC for Istio's namespace (istio-system by convention).
> 
> We have RBAC configured with EXCLUSION and its on by default for all namespaces. This worked fine in Istio 1.1, but b/c of the hidden RBAC Gateway feature, we have to explicitly exclude the Istio namespace for the Gateways to work the way they did in Istio 1.1.
> 
> I don't know if this new requirement is documented anywhere, but I think it would be helpful to include this in the upgrade instructions for Istio 1.2. Especially since the RBAC enabled Gateway feature isn't advertised in 1.2.

Oh, sorry for breaking your upgrade to 1.2.3. Yes, we added the RBAC support on ingress gateway in 1.2 but decided not to advertise it as we will soon release the new v1beta1 authorization policy in 1.4 that is going to deprecate the v1alpha1 RBAC policy: https://github.com/istio/api/blob/master/security/v1beta1/authorization.proto

We want to announce the ingress support with the new v1beta1 policy instead of the old v1alpha1 RBAC policy. I will update the 1.2 upgrade doc to add a note about this change, thanks for your report.

**Comment by yangminzhu** [comment]
@Jeffwan 

I feel a bit hard to understand your use case, could you give the diagram of your service and policy and what is your expected behavior? Is your question related to this github issue? I think the original issue is resolved in https://github.com/istio/istio/issues/14885#issuecomment-510256105.

> If I change to namespace level policy on the service directly, it's working perfectly.

Which policy you changed? and what is the expected flow?

**Comment by Jeffwan** [comment]
> @Jeffwan
> 
> I feel a bit hard to understand your use case, could you give the diagram of your service and policy and what is your expected behavior? Is your question related to this github issue? I think the original issue is resolved in [#14885 (comment)](https://github.com/istio/istio/issues/14885#issuecomment-510256105).
> 
> > If I change to namespace level policy on the service directly, it's working perfectly.
> 
> Which policy you changed? and what is the expected flow?

Hi @yangminzhu , sorry for the confusion. 

Here's the simple diagram. 
LoadBalancer  -> policy on svc:Istio-ingressgateway(ns: istio-system, AuthN)  ->  httpbin (AuthZ)

1. I am using a Load Balancer to manage outside traffic and once I pass authentication, it will add headers `x-oidc-header`.  
2. I create authentication policy on `Istio-ingressgateway` ( istio-ingressgateway.istio-system.svc.cluster.local). It will work for all services bound to the gateway, instead of for individual services. JWT Filter will validate decode and validate header `x-oidc-header`. 

3. I create serviceRole and serviceRoleBinding in httpbin namespace.  


My expectation is RBAC works for httpbin service but  I notice logs in `istio-proxy`  of httpbin shows dynamicMetadata is empty.

If I change authentication policy in the same namespace as httpbin. It's working. 
LoadBalancer  -> policy on svc:httpbin (ns: default, AuthN)  ->  httpbin (AuthZ)

**Comment by cdmurph32** [comment]
> Oh, sorry for breaking your upgrade to 1.2.3. Yes, we added the RBAC support on ingress gateway in 1.2 but decided not to advertise it as we will soon release the new v1beta1 authorization policy in 1.4 that is going to deprecate the v1alpha1 RBAC policy: https://github.com/istio/api/blob/master/security/v1beta1/authorization.proto
> 
> We want to announce the ingress support with the new v1beta1 policy instead of the old v1alpha1 RBAC policy. I will update the 1.2 upgrade doc to add a note about this change, thanks for your report.

@yangminzhu Does that mean that there is no documented way to use an ingress gateway in a an authorization enabled namespace after 1.2.3?  That is how we currently run our clusters with 1.1, with the services and ingress gateway in the same namespace.
I tried it out with 1.3.0. Even after adding a service account to the ingress gateway and binding a role to the service account I'm still not able to connect to the virtual services behind the gateway.
