### ISSUE TITLE
Frequent LDS ACK ERROR

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16273]
```
ADS:LDS: ACK ERROR 10.28.2.228:37402 sidecar~10.28.2.228~reviews-v2-664994896d-6lt5d.bookinfo~bookinfo.svc.cluster.local-36 (reviews-v2-664994896d-6lt5d.bookinfo) node:<id:"sidecar~10.28.2.228~reviews-v2-664994896d-6lt5d.bookinfo~bookinfo.svc.cluster.local" cluster:"reviews.bookinfo" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"bookinfo" > > fields:<key:"INCLUDE_INBOUND_PORTS" value:<string_value:"9080" > > fields:<key:"INSTANCE_IPS" value:<string_value:"10.28.2.228" > > fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:d408737154e866dcad4d6abf8aa7f1db611d8853" > > fields:<key:"ISTIO_VERSION" value:<string_value:"release-1.3-20190813-18-00" > > fields:<key:"POD_NAME" value:<string_value:"reviews-v2-664994896d-6lt5d" > > fields:<key:"app" value:<string_value:"reviews" > > fields:<key:"istio" value:<string_value:"sidecar" > > fields:<key:"istio.io/metadata" value:<struct_value:<fields:<key:"ip" value:<string_value:"10.28.2.228" > > fields:<key:"labels" value:<struct_value:<fields:<key:"app" value:<string_value:"reviews" > > fields:<key:"pod-template-hash" value:<string_value:"664994896d" > > fields:<key:"version" value:<string_value:"v2" > > > > > fields:<key:"name" value:<string_value:"reviews-v2-664994896d-6lt5d" > > fields:<key:"namespace" value:<string_value:"bookinfo" > > fields:<key:"platform_metadata" value:<struct_value:<fields:<key:"gcp_cluster_location" value:<string_value:"us-central1-a" > > fields:<key:"gcp_cluster_name" value:<string_value:"howardjohn" > > fields:<key:"gcp_project" value:<string_value:"howardjohn-istio" > > > > > > > > fields:<key:"pod-template-hash" value:<string_value:"664994896d" > > fields:<key:"version" value:<string_value:"v2" > > > locality:<region:"us-central1" zone:"us-central1-a" > build_version:"d408737154e866dcad4d6abf8aa7f1db611d8853/1.12.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"4ce63ab4-8d73-4d66-910f-56d6ecad7262" error_detail:<code:13 message:"Error adding/updating listener(s) virtualOutbound: cannot bind '0.0.0.0:15001': Address already in use, virtualInbound: cannot bind '0.0.0.0:15006': Address already in use" >
```

This seems to happen at start up typically then work ok

**Comment by hzxuzhonghu** [comment]
Maybe same, got this warning in envoy when i enable redis filter.

```
[2019-08-15 03:51:32.136][21][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_6379: Proto constraint validation failed (Using deprecated option 'envoy.config.filter.network.redis_proxy.v2.RedisProxy.PrefixRoutes.catch_all_cluster' from file redis_proxy.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.): catch_all_cluster: "outbound|6379||redis-cart.default.svc.cluster.local"
```

**Comment by howardjohn** [comment]
ah we need to fix that deprecated API usage

**Comment by hzxuzhonghu** [comment]
```
2019-08-15T03:55:13.717483Z	warn	ads	ADS:LDS: ACK ERROR 10.32.0.17:51584 sidecar~10.32.0.17~cli-57fc5649dd-ch9sf.default~default.svc.cluster.local-5 (cli-57fc5649dd-ch9sf.default) node:<id:"sidecar~10.32.0.17~cli-57fc5649dd-ch9sf.default~default.svc.cluster.local" cluster:"cli.default" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"default" > > fields:<key:"INCLUDE_INBOUND_PORTS" value:<string_value:"" > > fields:<key:"INSTANCE_IPS" value:<string_value:"10.32.0.17" > > fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:47e4559b8e4f0d516c0d17b233d127a3deb3d7ce" > > fields:<key:"ISTIO_VERSION" value:<string_value:"master-20190814-09-16" > > fields:<key:"POD_NAME" value:<string_value:"cli-57fc5649dd-ch9sf" > > fields:<key:"app" value:<string_value:"cli" > > fields:<key:"istio" value:<string_value:"sidecar" > > fields:<key:"istio.io/metadata" value:<struct_value:<fields:<key:"ip" value:<string_value:"10.32.0.17" > > fields:<key:"labels" value:<struct_value:<fields:<key:"app" value:<string_value:"cli" > > fields:<key:"pod-template-hash" value:<string_value:"57fc5649dd" > > > > > fields:<key:"name" value:<string_value:"cli-57fc5649dd-ch9sf" > > fields:<key:"namespace" value:<string_value:"default" > > > > > fields:<key:"pod-template-hash" value:<string_value:"57fc5649dd" > > > locality:<> build_version:"47e4559b8e4f0d516c0d17b233d127a3deb3d7ce/1.12.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"23f12db4-4f13-4b21-9eba-216ac4485a9b" error_detail:<code:13 message:"Error adding/updating listener(s) 0.0.0.0_6379: Proto constraint validation failed (Using deprecated option 'envoy.config.filter.network.redis_proxy.v2.RedisProxy.PrefixRoutes.catch_all_cluster' from file redis_proxy.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.): catch_all_cluster: \"outbound|6379||redis-cart.default.svc.cluster.local\"\n" > 

```

**Comment by hzxuzhonghu** [comment]
Let me have a fix for it.

**Comment by eightnoteight** [comment]
not sure if related to this error but I'm getting has unknown fields error
```
2019-08-15T15:13:07.178049Z	warn	ads	ADS:LDS: ACK ERROR 10.50.11.98:45384 sidecar~10.50.11.98~deployment-zservices-srinivas-eks-zdev-net-687dcfcfb9-c2rzk.dev~dev.svc.istio.zeks.io-103 (deployment-zservices-srinivas-eks-zdev-net-687dcfcfb9-c2rzk.dev) version_info:"2019-08-14T13:40:10Z/48" node:<id:"sidecar~10.50.11.98~deployment-zservices-srinivas-eks-zdev-net-687dcfcfb9-c2rzk.dev~dev.svc.istio.zeks.io" cluster:"istio-proxy.dev" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"dev" > > fields:<key:"INCLUDE_INBOUND_PORTS" value:<string_value:"15005" > > fields:<key:"INSTANCE_IPS" value:<string_value:"10.50.11.98" > > fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:d408737154e866dcad4d6abf8aa7f1db611d8853" > > fields:<key:"ISTIO_VERSION" value:<string_value:"master-20190813-09-16" > > fields:<key:"POD_NAME" value:<string_value:"deployment-zservices-srinivas-eks-zdev-net-687dcfcfb9-c2rzk" > > fields:<key:"app.kubernetes.io/component" value:<string_value:"user-zdevs-pods" > > fields:<key:"app.kubernetes.io/instance" value:<string_value:"srinivas-eks-zdev-net" > > fields:<key:"app.kubernetes.io/managed-by" value:<string_value:"terraform" > > fields:<key:"app.kubernetes.io/name" value:<string_value:"srinivas-eks-zdev-net-pod" > > fields:<key:"app.kubernetes.io/part-of" value:<string_value:"user-zdevs" > > fields:<key:"app.kubernetes.io/version" value:<string_value:"0.0.1-alpha" > > fields:<key:"istio" value:<string_value:"sidecar" > > fields:<key:"istio.io/metadata" value:<struct_value:<fields:<key:"ip" value:<string_value:"10.50.11.98" > > fields:<key:"labels" value:<struct_value:<fields:<key:"app.kubernetes.io/component" value:<string_value:"user-zdevs-pods" > > fields:<key:"app.kubernetes.io/instance" value:<string_value:"srinivas-eks-zdev-net" > > fields:<key:"app.kubernetes.io/managed-by" value:<string_value:"terraform" > > fields:<key:"app.kubernetes.io/name" value:<string_value:"srinivas-eks-zdev-net-pod" > > fields:<key:"app.kubernetes.io/part-of" value:<string_value:"user-zdevs" > > fields:<key:"app.kubernetes.io/version" value:<string_value:"0.0.1-alpha" > > fields:<key:"pod-template-hash" value:<string_value:"687dcfcfb9" > > fields:<key:"zeks.io/environment" value:<string_value:"dev" > > > > > fields:<key:"name" value:<string_value:"deployment-zservices-srinivas-eks-zdev-net-687dcfcfb9-c2rzk" > > fields:<key:"namespace" value:<string_value:"dev" > > > > > fields:<key:"pod-template-hash" value:<string_value:"687dcfcfb9" > > fields:<key:"sidecar.istio.io/inject" value:<string_value:"true" > > fields:<key:"zeks.io/environment" value:<string_value:"dev" > > fields:<key:"zeks.io/owner-team" value:<string_value:"sre@zomato.com" > > > locality:<> build_version:"d408737154e866dcad4d6abf8aa7f1db611d8853/1.12.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"9a1ce12c-ccc2-4a43-b683-b90ef88ed900" error_detail:<code:13 message:"Protobuf message (type envoy.api.v2.Listener) has unknown fields" >
```

any fix for this problem?

**Comment by howardjohn** [comment]
@eightnoteight can you provide pilot version and the version of the proxy?

**Comment by howardjohn** [comment]
Nevermind I forgot I can just look at the metadata.. looks like `master-20190813-09-16` for the proxy.. that is weird, I would only expect that with an older proxy.

It doesn't say what the unknown field is which is annoying. Do you have config we can produce it with?

**Comment by kyessenov** [comment]
It's probably the field I added to xDS `traffic_direction` https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/lds.proto

**Comment by howardjohn** [comment]
ok we probably need to guard it with proxy version GE 13. Thanks

**Comment by kyessenov** [comment]
Do we still not enable allowing unknown fields?

**Comment by howardjohn** [comment]
It is set, it doesn't seem to work though

```
2019-08-15T15:35:57.250446Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster details.book --service-node sidecar~10.28.3.214~details-v1-7964b4bb49-gtrpf.book~book.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error --concurrency 2]
```

**Comment by kyessenov** [comment]
File a bug in envoy please. It the field is set and not respected, it has a potential for an outage.

**Comment by howardjohn** [comment]
ok, let me get a minimal reproducer. I always thought that field just meant the bootstrap or something since we have had this problem for a while, but docs seem to indicate otherwise

> (optional) This flag disables validation of protobuf configurations for unknown fields. By default, the validation is enabled. For most deployments, the default should be used which ensures configuration errors are caught upfront and Envoy is configured as intended. However in cases where Envoy needs to accept configuration produced by newer control planes, effectively ignoring new features it does not know about yet, this can be disabled.

**Comment by kyessenov** [comment]
It shouldn't matter if it's in bootstrap or xDS. That was the original goal when I initially added the field, since it's generally confusing where the line is between JSON/proto.

**Comment by howardjohn** [comment]
interesting, seems broken in the envoy version we used, but fixed at HEAD (56d03e0bd106e933ece6201439bbf4d4208f39a5). will try to see what fixed it

**Comment by howardjohn** [comment]
@kyessenov Created https://github.com/envoyproxy/envoy/issues/7936

**Comment by howardjohn** [comment]
Confirmed in Istio land that *removing* --allow-unknown-fields actually fixes this...

**Comment by duderino** [comment]
The original LDS ACK errors are still an issue for 1.3 and since this is a regression it's a release blocker.

The fixes on this issue are for the unrelated "Protobuf message (type envoy.api.v2.Listener) has unknown fields" warning.

**Comment by lambdai** [comment]
ack

**Comment by lambdai** [comment]
I repeated kill envoy process with kill -9 but I haven't reproduce. 
Is `cannot bind ` permanent or it would disappear after envoy restarts?

**Comment by howardjohn** [comment]
I haven't been able to reproduce for a bit, will play around some more and try

**Comment by howardjohn** [comment]
After trying a lot I have been unable to reproduce. Will reopen and prioritize if I can trigger this again
