### ISSUE TITLE
Unable to access the Kubernetes apiserver when injecting the istio_proxy sidecar

### ISSUE THREAD

**Issue by secat** [istio/istio#1685]
When I inject the `istio_proxy` sidecar, my pod's main container which needs to access the Kubernetes apiserver can't reach it and receives socket errors:
```
fleet/svc/index/service/service.go:49: Failed to list *v1beta1.Ingress: Get https://10.0.0.1:443/apis/extensions/v1beta1/namespaces/fleet/ingresses?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
```

Here are some error logs from the `istio_proxy` sidecar:
```
[2017-11-08 13:06:45.064][15][warning][config] external/envoy/source/server/listener_manager_impl.cc:248] error adding listener: 'tcp_172.17.0.13_9999' has duplicate address '172.17.0.13:9999' as existing listener
[2017-11-08 13:06:45.064][15][warning][upstream] external/envoy/source/server/lds_subscription.cc:65] lds: fetch failure: error adding listener: 'tcp_172.17.0.13_9999' has duplicate address '172.17.0.13:9999' as existing listener
```

The istio version used are:
- 0.2.10
- 0.2.12

The Kubernetes version is 1.7.5

**Comment by sbezverk** [comment]
@secat I tried to access api server from the main container by using this command:
curl -k -X GET \
  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
  https://$KUBERNETES_PORT_443_TCP_ADDR:$KUBERNETES_SERVICE_PORT_HTTPS

And I do not see any issue. The difference here is istio version, I am using master version. Is there any chance you could try your application with the lates istio bits?

**Comment by GregHanson** [comment]
@secat are you still seeing this problem on istio version 0.5.1 or later?

**Comment by secat** [comment]
@GregHanson I am currently updating my system in order to evaluate istio version 0.5.1. As soon as I am done, I will let you know.

Thank you.

**Comment by secat** [comment]
@GregHanson I am still receiving errors of type:
```
Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/fleet/configmaps?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: connection refused
```

with istio version 0.5.1.

Here is an example of the sidecar that was injected with `istioctl kube-inject`:
```
  - args:
    - proxy
    - sidecar
    - --configPath
    - /etc/istio/proxy
    - --binaryPath
    - /usr/local/bin/envoy
    - --serviceCluster
    - istio-proxy
    - --drainDuration
    - 2s
    - --parentShutdownDuration
    - 3s
    - --discoveryAddress
    - servicemesh-pilot.istio-system:15003
    - --discoveryRefreshDelay
    - 1s
    - --zipkinAddress
    - zipkin.fleet:9411
    - --connectTimeout
    - 1s
    - --statsdUdpAddress
    - servicemesh-mixer.istio-system:9125
    - --proxyAdminPort
    - "15000"
    - --controlPlaneAuthPolicy
    - NONE
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: docker.io/istio/proxy:0.5.1
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    resources: {}
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /etc/certs/
      name: istio-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-bkzwc
      readOnly: true
```

**Comment by secat** [comment]
@GregHanson I finally was able to fix the problem on my side: I needed to create a `serviceaccount` with the right `role` and `rolebinding` for my deployment.

Therefore, the `istio-proxy` sidecar inherits from this `serviceaccount` and my application can now access the API Server.

You can consider this issue as fixed.

**Comment by nmnellis** [comment]
@secat Im experiencing a similar issue with crds but my application works fine without istio (aka permissions are good). when i inject the sidecar i get the error. didnt you say it worked without the sidecar?

```
Post https://100.64.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 100.64.0.1:443: getsockopt: connection refused
```

**Comment by secat** [comment]
@nmnellis In the past we were using a `rolebinding` based on the `admin-editor` role (installed on minikube and GKE clusters). This was kind of a hack in order for our runtime to access the API Server.

When we enabled the istio-proxy sidecar, this hack was not working anymore.

As explain above, using a proper `role`, `rolebinding`, and `serviceaccount` fixed our API Server access problem with the istio-proxy sidecar.

**Comment by nmnellis** [comment]
Thanks, i upgraded to 0.6.0 and the issue went away

**Comment by vaibhhavv** [comment]
Hello @secat @nmnellis 

We are using Istio v1.18.0 and Kiali v1.67.0 on two different namespaces.
I am facing below issue, We have tried adding above sidecar crd, service entry crd and destination entry crd too mentioned in `https://github.com/istio/istio/issues/8696#issuecomment-857441571`  but I am still not able to resolve the issue with Kiali and and below is the error log, could you please check and let me know what restriction can be on AKS cluster and how I can it get resolved?
```

{"level":"info","time":"2023-09-12T06:51:26Z","message":"Adding a RegistryRefreshHandler"}
2023/09/12 06:51:26 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
2023-09-12T06:51:26Z INF Kiali: Version: v1.67.0, Commit: e150adeb70aed909c41d3e964bc15b2b9ee7cccd, Go: 1.19.8
2023-09-12T06:51:26Z DBG Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml]
2023-09-12T06:51:26Z DBG Reading YAML config from [/kiali-configuration/config.yaml]
2023-09-12T06:51:26Z DBG Custom dashboards [count=20, enabled=true]: envoy,go,kiali,micrometer-1.0.6-jvm,micrometer-1.0.6-jvm-pool,micrometer-1.1-jvm,microprofile-1.1,microprofile-x.y,nodejs,quarkus,springboot-jvm,springboot-jvm-pool,springboot-tomcat,thorntail,tomcat,vertx-client,vertx-eventbus,vertx-jvm,vertx-pool,vertx-server
2023-09-12T06:51:26Z DBG Rest perf config QPS: 175.000000 Burst: 200
2023-09-12T06:51:26Z WRN Cannot resolve local cluster name. Err: Get "https://10.67.224.1:443/apis/apps/v1/namespaces/istio-system/deployments/istiod": dial tcp 10.67.224.1:443: connect: connection refused. Falling back to 'Kubernetes'
2023-09-12T06:51:26Z INF Using authentication strategy [token]
2023-09-12T06:51:26Z INF Some validation errors will be ignored [KIA1201]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2023-09-12T06:51:26Z DBG Rest perf config QPS: 175.000000 Burst: 200
2023-09-12T06:51:26Z INF Initializing Kiali Cache
2023-09-12T06:51:26Z INF Adding a RegistryRefreshHandler
2023-09-12T06:51:26Z DBG [Kiali Cache] Using 'cluster' scoped Kiali Cache
2023-09-12T06:51:26Z WRN Error checking Istio API configuration: Get "https://10.67.224.1:443/apis/networking.istio.io": dial tcp 10.67.224.1:443: connect: connection refused
2023-09-12T06:51:26Z WRN Error checking Kubernetes Gateway API configuration: Get "https://10.67.224.1:443/apis/gateway.networking.k8s.io": dial tcp 10.67.224.1:443: connect: connection refused
```

**Comment by sterziev88** [comment]
Hi @vaibhhavv Do you resolve that errors? I see the same in my Kiali logs...

**Comment by vaibhhavv** [comment]
Hi @sterziev88, yes on my end the issue is resolved.
I remember it was due to version compatibility of istio & kiali , look [here](https://kiali.io/docs/installation/installation-guide/prerequisites/)

I would suggest you whatever version you are deploying of istio and kiali:
1. To first check their compactibility
2. Check the versions of Istio & Kiali which is actually deployed after your deployments, 
      => login on kiali **>** ? icon on top right **>** About **>** You can see what versions of Istio & Kiali is actually installed.
Most of the time we think we are deploying correct version, but in the backend its actually not.

**Comment by sterziev88** [comment]
Thanks @vaibhhavv I see this 
![image](https://github.com/istio/istio/assets/66157650/f0ecd8f5-4ed4-49c7-abee-afbd4ce94ee1)
which is strange because I installed istio with helm chart and there my istiod version is 1.20 ...
Even more how I see istio versio 1.22 as the master version according the documentation is 1.21 ... 
Maybe I miss something!

**Comment by vaibhhavv** [comment]
Exactly! @sterziev88 
That was my same situation when I faced this issue.
No need to worry, I will give you the trick.

Whatever version you want to deploy of respective Istio & Kiali, in the helm chart values file, wherever you can see a parameter called `tag`. That by default comes parametrised with the latest version. You can update that with the version you want to deploy for respective tools and your setup will work.

**Comment by sterziev88** [comment]
Thanks @vaibhhavv I set the tag and hub and now "WRN Error checking Kubernetes Gateway API configuration: Get" disappeared.
My Kiali is 1.83 and my Istio 1.21 but I still see this

> 2024-04-17T06:28:49Z INF Kiali: Version: v1.83.0, Commit: 6bbef003ec097d104a9120588841eada9937fd75, Go: 1.20.10
2024/04/17 06:28:49 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2024-04-17T06:28:49Z INF Using authentication strategy [token]
2024-04-17T06:28:49Z INF Some validation errors will be ignored [KIA1301]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2024-04-17T06:28:49Z INF Initializing Kiali Cache
2024-04-17T06:28:49Z WRN Error checking Istio API configuration: Get "https://172.20.0.1:443/apis/networking.istio.io": dial tcp 172.20.0.1:443: connect: connection refused

and then I see this 

> 2024-04-17T06:29:51Z ERR K8s Cache [Kubernetes] is not found or is not accessible for Kiali: goroutine 1177 [running]:

Do you have an idea how I can fix that? 
:)

>

**Comment by vaibhhavv** [comment]
@sterziev88, It should not give any error after that atleast. :(
I would sugest you to try the Istio `1.21` with Kiali `1.79.0` and test if its the same case or not.

**Comment by sterziev88** [comment]
Hi @vaibhhavv  I fixed the error but at the moment I see metrics only for prometheus namespace and nothing for the namespace where are deployed my applications ( with virtualservices and gateway in it ). Do you have an idea why? 
:)

**Comment by vaibhhavv** [comment]
@sterziev88, have you enabled istio-injection for all of your namespaces? and side cars are running with evry pods in those namespace?

btw out of curiosity, how did you resolved it?

**Comment by sterziev88** [comment]
@vaibhhavv Yes, I have istio-injection for that specific namespace and there are sidecars for all pods.

I resolve it as I added:
deployment:
          pod_annotations:
            proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

**Comment by vaibhhavv** [comment]
@sterziev88 , do you see any error for that ns?

**Comment by sterziev88** [comment]
Nope, I think is related to Prometheus, because at the moment when I check Prometheus dashboard I am able to see information for istio_responce and istio_requests but only for Prometheus namespace nothing related to the namespace where are my applications.. So I think the problem is related to istio telemetry configuration

**Comment by vaibhhavv** [comment]
ohh okay @sterziev88.
I haven't got such problem yet and I also do have prometheus with istio and it works perfect. May be you can create an issue on istio regarding this, and may be someone can provide the solution.
