### ISSUE TITLE
Galley 1.3 + Pilot 1.4 incompatible

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16958]
Galley running 1.3 images cannot talk to a pilot running master images

Pilot logs:
```
2019-09-10T02:56:25.776547Z     info    mcp     (re)trying to establish new MCP sink stream
2019-09-10T02:56:25.776671Z     info    mcp     New MCP sink stream created
2019-09-10T02:56:25.777803Z     error   mcp     Error receiving MCP resource: rpc error: code = InvalidArgument desc = unsupported collection "istio/security/v1beta1/authorizationpolicies"
2019-09-10T02:56:25.777890Z     error   mcp     Error receiving MCP response: rpc error: code = InvalidArgument desc = unsupported collection "istio/security/v1beta1/authorizationpolicies"
2019-09-10T02:56:26.778140Z     info    mcp     (re)trying to establish new MCP sink stream
2019-09-10T02:56:26.778269Z     info    mcp     New MCP sink stream created
2019-09-10T02:56:26.779578Z     error   mcp     Error sending MCP request: EOF
```

This means it is impossible to canary a new version of Pilot.

@costinm @yangminzhu @ozevren

**Comment by yangminzhu** [comment]
@ozevren Should we make Galley to ignore the request for unknown CRD? Otherwise it seems this will be a problem whenever we're adding a new CRD.

**Comment by ozevren** [comment]
This is fixed in the new config pipeline, but it is not enabled yet. Galley
will not wait for CRDs, and if there is a missing CRD then it will simply
work as if it is empty. If the CRDs change, then it will reset its own
state internally to pick up the changes.

The flag is --useOldProcessor. There needs to be more testing before we can
enable it in 1.4.

**Comment by ozevren** [comment]
To clarify: to fix the scenario you mention, we will need to change the MCP
stack to return a response for the unrecognized request (that's where the
behavior is resolved). However, doing so will not allow the new CRD to be
picked-up by Galley when it arrives. The fix I mentioned above allows that.

**Comment by yangminzhu** [comment]
@ozevren So we have a proper fix in Galley but is disabled by default but it seems it's not ready to be enabled in 1.3 and needs more test? The flag `--useOldProcessor` seems strange to me because it fixes the issue but the name is "--use**Old**Processor", is the issue caused by some new behavior in Galley and we're fixing it by disabling the new behavior?

@howardjohn  Do we still have the problem if we upgrade galley to 1.4 first and then pilot? I'm not sure what we can do from pilot side considering the side effect mentioned by oz.

**Comment by ozevren** [comment]
Is there a document that describes the scenario in more detail?

**Comment by howardjohn** [comment]
Seems like there is already a fix for this, and there is not a huge need for this -- we will just need to make sure users update both galley and pilot together, so I think we can close
