### ISSUE TITLE
DestinationRule analyzers

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17507]
Analyzers checking destination rule issues:

Kiali rules that cover this:
https://www.kiali.io/documentation/validations/#_more_than_one_destination_rule_for_the_same_host_subset_combination
https://www.kiali.io/documentation/validations/#_this_subset_s_labels_are_not_found_in_any_matching_host

(Analyzers checking mTLS stuff related to destination rules are currently tracked in https://github.com/istio/istio/issues/17501)

**Comment by burmanm** [comment]
You can assign this one to me.

**Comment by sushicw** [comment]
Done. Thanks for volunteering!

**Comment by sushicw** [comment]
Let's also make sure we cover basic "does it exist" checks for the specified hosts in destination rules.

**Comment by sushicw** [comment]
PR #18364 by @burmanm is still WIP, removing stale marker.

**Comment by esnible** [comment]
@burmanm I changed this to 1.6.  Are you still working on this.

Also re-opening because the policy bot closed it for "no activity" as soon as I started doing activity!

**Comment by burmanm** [comment]
Either me or Xavi will finish it. Although I can't really tell what is
still missing..
