### ISSUE TITLE
Istioctl/operator egress gateway issues (duplicate sdsudspath, missing istio-certs)

### ISSUE THREAD

**Issue by LukaszRacon** [istio/istio#20082]
**Bug description**
Istioctl/operator creates egress gateway with duplicate `sdsudspath` volume and is missing `istio-certs` volume and volumeMount.

Duplicate `sdsudspath` cases error in istio-operator:
`istio-operator-... error   error occurred reconciling resource: Deployment.apps "istio-egressgateway" is invalid: spec.template.spec.volumes[2].name: Duplicate value: "sdsudspath"`

Missing `istio-certs` volume and volumeMount causes error in istio-egressgateway:
`istio-egressgateway-...-...[Envoy (Epoch 0)] [...][15][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/certs/cert-chain.pem`

**Steps to reproduce the bug**
```
istioctl manifest generate -f - <<EOF
IstioControlPlane
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio-control-plane
  namespace: istio-operator
spec:
  profile: sds

  gateways:
    components:
      egressGateway:
        enabled: true

  values:
    gateways:
      istio-egressgateway:
        enabled: true
EOF
```
creates istio-egressgateway deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: istio
  name: istio-egressgateway
  namespace: istio-system
spec:
 ...
  template:
    spec:
      containers:
      - image: docker.io/istio/proxyv2:1.4.3
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ...
        volumeMounts:
        - mountPath: /var/run/sds
          name: sdsudspath
          readOnly: true
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          readOnly: true
      volumes:
      - hostPath:
          path: /var/run/sds
        name: sdsudspath
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - hostPath:
          path: /var/run/sds
        name: sdsudspath
      - name: egressgateway-certs
        secret:
          optional: true
          secretName: istio-egressgateway-certs
      - name: egressgateway-ca-certs
        secret:
          optional: true
          secretName: istio-egressgateway-ca-certs
```

**Unexpected behavior**
With duplicated `sdsudspath` volume istio operator fails to create istio-egressgateway deployment.

`istio-certs` volume and `/etc/certs/` volumeMount are needed for Egress Gateway's TLS (or docs need to be updated).

https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
    ...
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

**Version**
istioctl 1.4.3 (istio-certs exist in istioctl 1.4.2; sdsudspath is an older issue)

**Temporary Workaround**
Override volume/volumeMount with k8s overlay:
```
IstioControlPlane
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio-control-plane
  namespace: istio-operator
spec:
  profile: sds

  gateways:
    components:
      egressGateway:
        enabled: true
        k8s:
          overlays:
            - kind: Deployment
              name: istio-egressgateway
              patches:
                - path: spec.template.spec.volumes
                  value:
                    - name: istio-token
                      projected:
                        sources:
                          - serviceAccountToken:
                              audience: istio-ca
                              expirationSeconds: 43200
                              path: istio-token
                    - hostPath:
                        path: /var/run/sds
                      name: sdsudspath
                    - name: istio-certs
                      secret:
                        optional: true
                        secretName: istio.default
                    - name: egressgateway-certs
                      secret:
                        optional: true
                        secretName: istio-egressgateway-certs
                    - name: egressgateway-ca-certs
                      secret:
                        optional: true
                        secretName: istio-egressgateway-ca-certs
                - path: spec.template.spec.containers.[name:istio-proxy].volumeMounts
                  value:
                    - mountPath: /var/run/sds
                      name: sdsudspath
                      readOnly: true
                    - mountPath: /var/run/secrets/tokens
                      name: istio-token
                    - mountPath: /etc/certs
                      name: istio-certs
                      readOnly: true
                    - mountPath: /etc/istio/egressgateway-certs
                      name: egressgateway-certs
                      readOnly: true
                    - mountPath: /etc/istio/egressgateway-ca-certs
                      name: egressgateway-ca-certs
                      readOnly: true

  values:
    gateways:
      istio-egressgateway:
        enabled: true
```

**Comment by haf-afa** [comment]
It doesn't need triage; it's actually an issue.

**Comment by haf-afa** [comment]
Will this be fixed in 1.4.4?

**Comment by incfly** [comment]
@myidpt @ostromart can any of you verify this is fixed in new release or not?

**Comment by haf-afa** [comment]
Still an issue in the latest 1.4.x branches

**Comment by iftachsc** [comment]
still an issue in 1.5.1

**Comment by amckee23** [comment]
We are still seeing this issue in 1.5.4 Is there any way to enable Workload -> Egress gateway MTLS?

**Comment by amckee23** [comment]
For what its worth now this is closed. We managed to fix this / find a work around.  The core issue we faced appears to have been following the guide on: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/. set up subset networking rules which when removed allowed for workload -> egress-gateway mtls to resolve.
