### ISSUE TITLE
Istio.service in mesh expansion crashes and fails to restart

### ISSUE THREAD

**Issue by Docteur-RS** [istio/istio#21460]
### Bug description
I'm using the sidecar.deb of istio mesh expansion.  
After some time the **istio.service fails** and cannot be restarted.  

To fix the service, one has to restore the shared memory with the following command:
```shell
sudo rm /dev/shm/envoy_shared_memory_0
```
The service goes up immediately after.

This is a referenced issue in Envoy: [#4191](https://github.com/envoyproxy/envoy/issues/4195#issuecomment-415547470)

I include the following stacktrace from _/var/log/istio/istio.err.log_ but I'm not sure if there is a link with the Envoy problem.  
```
 cat /var/log/istio/istio.err.log
[Envoy (Epoch 0)] [2020-02-25 09:24:29.059][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:29:29.605][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:34:29.748][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:39:30.040][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:44:30.394][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:49:30.451][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:54:30.873][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 09:59:30.989][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 10:04:31.194][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 10:16:13.379][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 10:21:13.660][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 10:21:58.607][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 10:26:58.806][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-02-25 10:31:59.355][6365][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
```

### Expected behavior
Istio.service should not crash.  

### Steps to reproduce the bug
Unclear. Happens randomly.  

### Version
Istio sidecar.deb 1.4.3/1.4.4

### Environment where bug was observed (cloud vendor, OS, etc)
On premise.  
Mesh expansion VM : Ubuntu 14.04 / Debian stretch

**Comment by howardjohn** [comment]
The logs do not show any crash, but expected disconnects due to keepalives. Is there any logs of crash?

**Comment by Docteur-RS** [comment]
Unfortunately _/var/log/istio/istio.err.log_ was empty.  I guess that when the service went back up after I cleaned the shared memory, the logs were erased by systemd and the reboot of the service.  

The corruption of the shared memory happend 3 times to me. The last one happended over night...

Next time I'll check the logs **BEFORE** rebooting the service :-/

**Comment by Docteur-RS** [comment]
Wait... It happend again...

I copied the complete logs in [here](https://gist.github.com/Docteur-RS/f2299a03ecbe48ab81e4b8ae9a5ff0ea)

The main issue at hand seems to be the following:
```
[warning][config] [external/envoy/source/server/options_impl.cc:196] --allow-unknown-fields is deprecated, use --allow-unknown-static-fields instead.
[critical][assert] [external/envoy/source/server/hot_restart_impl.cc:45]panic: cannot open shared memory region /envoy_shared_memory_0 check user permissions. Error: File exists
```

**Comment by Docteur-RS** [comment]
And [here](https://gist.github.com/Docteur-RS/37f677f5ff9f4743a64e4ad8606fa5a5) is the logs from _/var/log/istio/istio.log_

The main issue seems to be:
```
warn    Epoch 0 terminated with an error: signal: aborted (core dumped)
warn    Aborted all epochs
error   Permanent error: budget exhausted trying to fulfill the desired configuration
error   cannot start the e with the desired configuration
```

**Comment by irisdingbj** [comment]
Have you check and make sure there is only one envoy running? Now the `istio.service` will be auto-restarted when it has failure so envoy will be restarted as well.

**Comment by irisdingbj** [comment]
`sudo rm /dev/shm/envoy_shared_memory_0` should fix this

**Comment by Docteur-RS** [comment]
I moved on so I can't check anymore.  

But as I explained in the original issue:
> After some time the istio.service fails and cannot be restarted.

Unfortunatly , auto-restarting the service probably won't fix the error.

---

And yes, removing the shared memory works as I also mentionned earlier :
> To fix the service, one has to restore the shared memory with the following command:
> `sudo rm /dev/shm/envoy_shared_memory_0`

But this is only treating the symptoms and does not fix the corruption itself.

**Comment by howardjohn** [comment]
It looks like this is breaking during hot restart. Since we no longer do hot restart,  I think this bug is not present. If I misunderstood please reopen. thanks
