### ISSUE TITLE
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s:

### ISSUE THREAD

**Issue by yaakov-berkovitch** [istio/istio#22319]
**Bug description**
Try to install last 1.5.0 version over Kubernetes 1.7, and consistently failed with error:
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: dial tcp 10.111.86.18:443: connect: no route to host (repeated 2 times)

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expect to see istio deployed over kubernetes.

**Steps to reproduce the bug**
istioctl manifest apply --set addonComponents.grafana.enabled=true

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version: 1.5.0.

kubectl version:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```
**How was Istio installed?**
curl -L https://istio.io/downloadIstio | sh -

**Environment where bug was observed (cloud vendor, OS, etc)**
Installation on premise - Centos 7

Full error output:

```
 istioctl manifest apply --set addonComponents.grafana.enabled=true
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
- Applying manifest for component IngressGateways...
- Applying manifest for component AddonComponents...
2020-03-19T12:39:04.197433Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component AddonComponents.
2020-03-19T12:39:07.010758Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component IngressGateways.

Component AddonComponents - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:


Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: dial tcp 10.111.86.18:443: connect: no route to host (repeated 1 times)


clusterrole.rbac.authorization.k8s.io/prometheus-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system created

serviceaccount/prometheus created
configmap/istio-grafana created
configmap/istio-grafana-configuration-dashboards-citadel-dashboard created
configmap/istio-grafana-configuration-dashboards-galley-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-mesh-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-performance-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-service-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-workload-dashboard created
configmap/istio-grafana-configuration-dashboards-mixer-dashboard created
configmap/istio-grafana-configuration-dashboards-pilot-dashboard created
configmap/prometheus created
deployment.apps/grafana created
deployment.apps/prometheus created
service/grafana created
service/prometheus created



Component IngressGateways - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: dial tcp 10.111.86.18:443: connect: no route to host (repeated 2 times)


serviceaccount/istio-ingressgateway-service-account created
deployment.apps/istio-ingressgateway created
poddisruptionbudget.policy/ingressgateway created
role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
service/istio-ingressgateway created




✘ Errors were logged during apply operation. Please check component installation logs above.

Error: failed to apply manifests: errors were logged during apply operation

```
Thanks.

**Comment by FrankPetrilli** [comment]
I am also experiencing this issue - applying istio 1.5.0 to a brand-new cluster created with kubeadm on Flatcar Linux, running Kubernetes v1.17.4 and Calico alone. No workloads have been applied, nor have other changes have been made. Attaching as much info as I can:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version
2020-03-19T20:16:18.563761Z     warn    will use `--remote=false` to retrieve version info due to `no Istio pods in namespace "istio-system"`
1.5.0

$ istioctl manifest generate > istio.yaml

# First pass of apply seems to hit a race condition with the namespace's existence
$ kubectl apply -f istio.yaml
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-reader-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-istio-system created
customresourcedefinition.apiextensions.k8s.io/meshpolicies.authentication.istio.io created
customresourcedefinition.apiextensions.k8s.io/policies.authentication.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/attributemanifests.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/handlers.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/instances.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/rules.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/clusterrbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/rbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceroles.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/servicerolebindings.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/adapters.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/templates.config.istio.io created
namespace/istio-system created
serviceaccount/istio-reader-service-account created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
deployment.apps/istio-ingressgateway created
poddisruptionbudget.policy/ingressgateway created
role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
service/istio-ingressgateway created
serviceaccount/istio-ingressgateway-service-account created
horizontalpodautoscaler.autoscaling/istiod created
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system created
clusterrole.rbac.authorization.k8s.io/istiod-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istiod-istio-system created
configmap/pilot-envoy-config created
configmap/istio created
deployment.apps/istiod created
configmap/istio-sidecar-injector created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector created
poddisruptionbudget.policy/istiod created
service/istio-pilot created
service/istiod created
serviceaccount/istiod-service-account created
validatingwebhookconfiguration.admissionregistration.k8s.io/istiod-istio-system created
validatingwebhookconfiguration.admissionregistration.k8s.io/istio-galley created
Error from server (NotFound): error when creating "istio.yaml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "istio.yaml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "istio.yaml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "istio.yaml": namespaces "istio-system" not found
[unable to recognize "istio.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "istio.yaml": no matches for kind "Sidecar" in version "networking.istio.io/v1alpha3", unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"]

# Try again
$ kubectl apply -f istio.yaml
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system unchanged
configmap/prometheus created
deployment.apps/prometheus created
service/prometheus created
serviceaccount/prometheus created
clusterrole.rbac.authorization.k8s.io/istio-reader-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-istio-system unchanged
customresourcedefinition.apiextensions.k8s.io/meshpolicies.authentication.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/policies.authentication.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/httpapispecs.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/httpapispecbindings.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/quotaspecs.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/quotaspecbindings.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/attributemanifests.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/handlers.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/instances.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/rules.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/clusterrbacconfigs.rbac.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/rbacconfigs.rbac.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/serviceroles.rbac.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/servicerolebindings.rbac.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/adapters.config.istio.io unchanged
customresourcedefinition.apiextensions.k8s.io/templates.config.istio.io unchanged
namespace/istio-system unchanged
serviceaccount/istio-reader-service-account unchanged
horizontalpodautoscaler.autoscaling/istio-ingressgateway unchanged
deployment.apps/istio-ingressgateway configured
poddisruptionbudget.policy/ingressgateway unchanged
role.rbac.authorization.k8s.io/istio-ingressgateway-sds unchanged
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds unchanged
service/istio-ingressgateway unchanged
serviceaccount/istio-ingressgateway-service-account unchanged
horizontalpodautoscaler.autoscaling/istiod unchanged
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istiod-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istiod-istio-system unchanged
configmap/pilot-envoy-config unchanged
configmap/istio unchanged
deployment.apps/istiod configured
configmap/istio-sidecar-injector unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector configured
poddisruptionbudget.policy/istiod unchanged
service/istio-pilot unchanged
service/istiod unchanged
serviceaccount/istiod-service-account unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/istiod-istio-system configured
validatingwebhookconfiguration.admissionregistration.k8s.io/istio-galley configured
unable to recognize "istio.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "Sidecar" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"

$ kubectl get crd
NAME                                          CREATED AT
adapters.config.istio.io                      2020-03-19T20:20:31Z
attributemanifests.config.istio.io            2020-03-19T20:20:31Z
authorizationpolicies.security.istio.io       2020-03-19T20:20:31Z
bgpconfigurations.crd.projectcalico.org       2020-03-19T19:44:38Z
bgppeers.crd.projectcalico.org                2020-03-19T19:44:38Z
blockaffinities.crd.projectcalico.org         2020-03-19T19:44:38Z
clusterinformations.crd.projectcalico.org     2020-03-19T19:44:38Z
clusterrbacconfigs.rbac.istio.io              2020-03-19T20:20:31Z
destinationrules.networking.istio.io          2020-03-19T20:20:31Z
envoyfilters.networking.istio.io              2020-03-19T20:20:31Z
felixconfigurations.crd.projectcalico.org     2020-03-19T19:44:38Z
gateways.networking.istio.io                  2020-03-19T20:20:31Z
globalnetworkpolicies.crd.projectcalico.org   2020-03-19T19:44:38Z
globalnetworksets.crd.projectcalico.org       2020-03-19T19:44:38Z
handlers.config.istio.io                      2020-03-19T20:20:31Z
hostendpoints.crd.projectcalico.org           2020-03-19T19:44:38Z
httpapispecbindings.config.istio.io           2020-03-19T20:20:31Z
httpapispecs.config.istio.io                  2020-03-19T20:20:31Z
instances.config.istio.io                     2020-03-19T20:20:31Z
ipamblocks.crd.projectcalico.org              2020-03-19T19:44:38Z
ipamconfigs.crd.projectcalico.org             2020-03-19T19:44:38Z
ipamhandles.crd.projectcalico.org             2020-03-19T19:44:38Z
ippools.crd.projectcalico.org                 2020-03-19T19:44:38Z
meshpolicies.authentication.istio.io          2020-03-19T20:20:31Z
networkpolicies.crd.projectcalico.org         2020-03-19T19:44:38Z
networksets.crd.projectcalico.org             2020-03-19T19:44:38Z
peerauthentications.security.istio.io         2020-03-19T20:20:31Z
policies.authentication.istio.io              2020-03-19T20:20:31Z
quotaspecbindings.config.istio.io             2020-03-19T20:20:31Z
quotaspecs.config.istio.io                    2020-03-19T20:20:31Z
rbacconfigs.rbac.istio.io                     2020-03-19T20:20:31Z
requestauthentications.security.istio.io      2020-03-19T20:20:31Z
rules.config.istio.io                         2020-03-19T20:20:31Z
serviceentries.networking.istio.io            2020-03-19T20:20:31Z
servicerolebindings.rbac.istio.io             2020-03-19T20:20:31Z
serviceroles.rbac.istio.io                    2020-03-19T20:20:31Z
sidecars.networking.istio.io                  2020-03-19T20:20:31Z
templates.config.istio.io                     2020-03-19T20:20:31Z
virtualservices.networking.istio.io           2020-03-19T20:20:31Z
```

**Comment by taylorreece** [comment]
If you `kubectl get pods -n istio-system`, is istiod running? If not, why not? Out of resources maybe?

**Comment by yaakov-berkovitch** [comment]
Thanks for your rpely.
Following output of the command kubectl get pods -n istio-system
```
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-5cc7f86765-gjq8r                1/1     Running   0          17s
istio-ingressgateway-78f757846c-svd5r   0/1     Running   0          14s
istiod-65c5b8df9d-z5wmq                 1/1     Running   2          3m8s
prometheus-6fd77b7876-48mhx             1/2     Running   0          17s

```
Following the error in the log for the istio-ingressgateway
```
2020-03-20T10:24:34.938256Z	error	citadelclient	Failed to create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.106.119.68:15012: i/o timeout"
2020-03-20T10:24:34.938263Z	error	cache	node:router~10.244.0.49~istio-ingressgateway-78f757846c-svd5r.istio-system~istio-system.svc.cluster.local-6 resource:default request:249bc1b4-2aa1-41ca-bc9c-3cdddd4705e0 CSR retrial timed out: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.106.119.68:15012: i/o timeout"

```
I have currently 3GB free on my machine. Is it enough ? The problem is perhaps the CPU, not enough vCPU, and so it failed it timeout ?

Thanks.

**Comment by taylorreece** [comment]
For docker desktop, 4 cores and 8GB of RAM is recommended.  If you `kubectl get deployment -n istio-system -o yaml` are there any issues shown related to any of the deployments (low resources, etc)?

https://istio.io/docs/setup/platform-setup/docker/

**Comment by yaakov-berkovitch** [comment]
I was not accurate on my previous answer. I have a machine with 4 vCPU and 8GB RAM, What I wrote is  that after istio is deployed i still have 3GB free. I even did some cleanup and have now 5GB free.
Also i'm not running on windows but on centos 7, and docker version is: Docker version 19.03.5, build 633a0ea

The command does not report for low resource or any error related error to resources. I attached the output of the command.
[istio-deployment.txt](https://github.com/istio/istio/files/4363646/istio-deployment.txt)
 
Thanks.

**Comment by yaakov-berkovitch** [comment]
Just tried the 1.5.1 and all is running fine. Looks that the issue has been resolved .

**Comment by DesistDaydream** [comment]
i have same issue.
k8s: 1.17.3
istio: 1.5.1


A little different：istio-ingressgateway is running.
But the log of kube-apiserver still reports errors：
```
W0401 09:49:27.065594       1 dispatcher.go:128] Failed calling webhook, failing open validation.istio.io: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded
E0401 09:49:27.065620       1 dispatcher.go:129] failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded
```

the log of istiod reports info:
```
2020-04-01T09:51:27.101082Z	info	validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
2020-04-01T09:51:27.101740Z	info	validationController	validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=205973) is up-to-date. No change required.
2020-04-01T09:51:27.101773Z	info	validationController	Reconcile(enter): retry dry-run creation of invalid config
```

**Comment by feliperfmarques** [comment]
This issue can also to be a problem of webhook validation. For webhook works, firewall rule needs setting to port 15017 instead of 9443 on Istio 1.5, as mentioned here #19532 (comment). Try add this firewall rule.

**Comment by lizongshen** [comment]
I'm facing the same problem, is there any update or work around to solve it?

**Comment by lizongshen** [comment]
> This issue can also to be a problem of webhook validation. For webhook works, firewall rule needs setting to port 15017 instead of 9443 on Istio 1.5, as mentioned here #19532 (comment). Try add this firewall rule.

I turned off the firewall and still encountered the same error

**Comment by kangxiaoning** [comment]
I also encountered the same problem. istio runs on the company's intranet, sorry for not being able to upload logs. 

Provide the following information to help diagnose
```
kubernetes version: 1.5.1
istio version: 1.5.2
```
The error occurred during the execution of `istioctl manifest apply --set profile=default --set hub=xxx --setvalues.tracing.jaeger.hub=xxx ...`, I only customized all the image hub address.

After installed, All pods are running, API Service log see the same error.

**Comment by guanw** [comment]
Think I also run into this trying bookinfo demo [here](https://istio.io/latest/docs/examples/bookinfo/)

![image](https://user-images.githubusercontent.com/7311035/85237989-e694e380-b3f8-11ea-90e2-366386fe6dd8.png)

Any updates?

**Comment by ragunathan23** [comment]
@feliperfmarques I am facing a similar issue with Centos 7 on-premise development. There is no firewall running and automatic sidecar injection for the pod is also failing. 

kubernetes version: 1.18.1
istio version : 1.5.2

Any help much appreciated.

Error:
Kube-api server:

-- Failed calling webhook, failing open validation.istio.io: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded

- istiod-logs:

validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
validationController	validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=205973) is up-to-date. No change required.
validationController	Reconcile(enter): retry dry-run creation of invalid config

**Comment by ragunathan23** [comment]
It's a flannel issue. For now able to fix the issue by changing the flannel backend to host-gw from vxlan. Not sure why it didn't work with vxlan. Thanks for @nustiueudinastea (Alex) for debugging the issue.

**Comment by cheferrari** [comment]
> @feliperfmarques I am facing a similar issue with Centos 7 on-premise development. There is no firewall running and automatic sidecar injection for the pod is also failing.
> 
> kubernetes version: 1.18.1
> istio version : 1.5.2
> 
> Any help much appreciated.
> 
> Error:
> Kube-api server:
> 
> -- Failed calling webhook, failing open validation.istio.io: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: context deadline exceeded
> 
> * istiod-logs:
> 
> validationController Not ready to switch validation to fail-closed: dummy invalid config not rejected
> validationController validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=205973) is up-to-date. No change required.
> validationController Reconcile(enter): retry dry-run creation of invalid config

Kubernetes version: v1.18.3
Istio 1.7.0

I also encountered the same problem

**Comment by hklohar** [comment]
I have encountered similar issue with 1.18.1 and istio 1.5.4
But issues was related to configuration of calico CNI 
Calico CNI with IP_AUTODETECTION_METHOD set to "interface=ens3" resolve the issue
