### ISSUE TITLE
In-place upgrade to 1.6.0 fails: wrong URL

### ISSUE THREAD

**Issue by vbergbauer** [istio/istio#24029]
**Bug description**

In-place upgrade of istio to 1.6.0 fails with 404 error.
```
istioctl upgrade --dry-run

Error: failed to generate Istio configs from file [] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz : 404 Not Found
```
Note that the fetch URL is indeed not valid, as it is missing the **-amd64** suffix
- Expected: https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz
- Real: https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux-amd64.tar.gz
The bug seems to be in file:
https://github.com/istio/istio/blob/975ff2f3224d6d5c31a0f63204730ea045455dd8/operator/cmd/mesh/upgrade.go#L59

**Expected behavior**
This should succeed:
```
istioctl upgrade --dry-run
```
Instead it fails:
```
Error: failed to generate Istio configs from file [] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz : 404 Not Found
```
**Steps to reproduce the bug**
```
istioctl upgrade --dry-run
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version
client version: 1.6.0
control plane version: 1.5.4
data plane version: 1.5.4 (12 proxies)
```

**How was Istio installed?**
```
 istioctl manifest apply
```
**Environment where bug was observed (cloud vendor, OS, etc)**
- Client: Ubuntu 16.04 on WSL 1
- Server: docker-desktop 2.3.0.2 (engine: 19.03.8)

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio/pull/23861 which didn't make it into 1.6.0 but is there now for 1.6.1 release.
For 1.6.0, you can still upgrade using istioctl install command (use the target version, just as for upgrade). Upgrade simply layers some checks on top of istioctl install to warn about removed fields and version compatibility. But, if you can wait for 1.6.1, it should be fixed in that version.

**Comment by ostromart** [comment]
There's still one lingering unexplained issue here. The upgrade command thinks the installed version is 1.6.0 per the error message, which is why it's trying to download what it believes is the "from" version as 1.6.0. But per version command, the actual installed version is 1.5.4. Assigning to @elfinhe to investigate this further.

**Comment by elfinhe** [comment]
Hi vbergbauer@, I cannot not reproduce the lingering wrong current version issue. can you help confirm that when using `istioctl upgrade`, the installed version is 1.5.4?

**Comment by vbergbauer** [comment]
Hello @elfinhe ,
It looks like I mixed two sets of upgrade in copying and pasting:
- From 1.5.4 to 1.6
- From 1.6 to 1.6

However, when trying the latest 1.6 commit (this time I am copying my shell verbatim), I still see the problem:
```

$ istio-1.6-alpha.51f1e4c2d368dd3acf3e3f21201d6d345bd83acf/bin/istioctl version
client version: 1.6-alpha.51f1e4c2d368dd3acf3e3f21201d6d345bd83acf
control plane version: 1.6.0
data plane version: 1.6.0 (22 proxies)

$ istio-1.6-alpha.51f1e4c2d368dd3acf3e3f21201d6d345bd83acf/bin/istioctl upgrade --dry-run -f small.yaml
2020-05-26T22:32:01.005136Z     info    proto: tag has too few fields: "-"
Control Plane - ingressgateway pod - istio-ingressgateway-569669bb67-cx426 - version: 1.6.0
Control Plane - pilot pod - istiod-788cf6c878-vdlmj - version: 1.6.0

2020-05-26T22:32:01.154427Z     warn    found 4 CRD of unsupported v1alpha1 security policy: [clusterrbacconfigs.rbac.istio.io rbacconfigs.rbac.istio.io servicerolebindings.rbac.istio.io serviceroles.rbac.istio.io]. The v1alpha1 security policy is no longer supported starting 1.6. It's strongly recommended to delete the CRD of the v1alpha1 security policy to avoid applying any of the v1alpha1 security policy in the unsupported version
Upgrade version check passed: 1.6.0 -> 1.6.0.

2020-05-26T22:32:01.551879Z     info    Error: failed to generate Istio configs from file [small.yaml] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz : 404 Not Found

Error: failed to generate Istio configs from file [small.yaml] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz : 404 Not Found
```

The content of `small.yaml` is:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: docker-desktop
spec:
  profile: default
  meshConfig:
    accessLogFile: '/dev/stdout'
    accessLogEncoding: JSON
    defaultConfig:
      tracing:
        sampling: 100
  addonComponents:
    grafana:
      enabled: true
      k8s:
        service:
          type: NodePort
          ports:
            - port: 3000
              nodePort: 32001
    prometheus:
      enabled: true
      k8s:
        service:
          type: NodePort
          ports:
            - port: 9090
              nodePort: 32002
    tracing:
      enabled: true
    kiali:
      enabled: true
      k8s:
        service:
          type: NodePort
          ports:
            - port: 20001
              nodePort: 32000
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous
        grafanaURL: http://localhost:32001/
      security:
        cert_file: ''
        private_key_file: ''
```

**Comment by elfinhe** [comment]
That makes sense. Thanks.

The expected URL is https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux-amd64.tar.gz

Looks like we are still missing the cpu type suffix.

**Comment by elfinhe** [comment]
The URL issue is fixed in https://github.com/istio/istio/pull/24050/.

**Comment by ostromart** [comment]
Per my earlier comment this is fixed in 1.6.1, I just verified it in the prerelease binary.
