### ISSUE TITLE
injection failed

### ISSUE THREAD

**Issue by lck0129** [istio/istio#24699]
**Bug description**

fresh install, K8S 1.18.3 with flannel  CNI, Istio 1.6.2

kubectl get rs
NAME                    DESIRED   CURRENT   READY   AGE
pod-v1-fc45947dd   1         0         0       49m

kubectl describe rs pod-v1-fc45947dd 
  Warning  FailedCreate  2m56s (x14 over 13m)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istiod.istio-system.svc:443/inject?timeout=30s: context deadline exceeded

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

finish injection  and start pods

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

istioctl  version
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (2 proxies)

**How was Istio installed?**

istioctl manifest apply --set profile=default \
--set values.global.mtls.enabled=false \
--set values.global.mtls.auto=true \
--set values.gateways.istio-egressgateway.enabled=false

**Environment where bug was observed (cloud vendor, OS, etc)**

CentOS Linux release 7.7.1908 (Core)

**Comment by howardjohn** [comment]
This indicates issues connecting to the pod from that api-server, likely due to some flannel config?

**Comment by lck0129** [comment]
> This indicates issues connecting to the pod from that api-server, likely due to some flannel config?

thanks for your reply, I am using this config
https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

**Comment by jnicholls** [comment]
I am also seeing this error during sidecar injection.

```
failed calling webhook "sidecar-injector.istio.io": Post https://istiod.istio-system.svc:443/inject?timeout=30s: context deadline exceeded
```

Apparently the service is unreachable from the api-server, for some reason. It is reachable from any other pod in the cluster, however. I too am using flannel.

**Comment by howardjohn** [comment]
I have added some extra steps to https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecar-injection that may helps. its also common for https_proxy variables on api server breaking this

**Comment by jnicholls** [comment]
Thanks for that write up @howardjohn.

```
~ $ kubectl get --raw /api/v1/namespaces/istio-system/services/https:istiod:https-webhook/proxy/inject -v4
I0618 16:54:50.276863   88276 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "404 page not found"
      }
    ]
  },
  "code": 404
}]
F0618 16:54:50.278391   88276 helpers.go:115] Error from server (NotFound): the server could not find the requested resource
```

```
$ kubectl -n istio-system get services
NAME     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                AGE
istiod   ClusterIP   100.67.179.92   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,53/UDP,853/TCP   4h43m
```

**Comment by lck0129** [comment]
tried calico everything works well, so it is flannel's problem.
https://github.com/coreos/flannel/issues/1259
fixed by  "change the working mode of flannel to 'host-gw' and install 'kube-state-metrics' "

**Comment by jnicholls** [comment]
I commented on the flannel ticket. Here it is as well.

> I am also running into this problem with Istio 1.6.2. This was not a problem with Istio 1.4.x. Can you explain what changed?
> 
> Can someone explain why kube-state-metrics would have any sort of effect on the api-server's ability to speak to an in-cluster service?

I haven't changed my flannel setup, at all, and thus something changed between Istio 1.4.x and Istio 1.6.2 (i.e the amalgamation of all the parts into `istiod`) that caused this to happen. Does anyone have any insight into what might have happened here that's architecturally different now?

**Comment by howardjohn** [comment]
One thing we found with users with private GKE clusters was the targetPort
for the webhooks moved from 9443 to 15017. targetPort usually doesn't
matter but there is a k8s feature which will bypass the Service for
webhooks, so it actually *does* here. so firewall rules for 1.4 (on port
9443) no longer work. Maybe something similar?

**Comment by jnicholls** [comment]
Ok, thanks. This cluster is in AWS and at least from the standpoint of security groups, all traffic is allowed node-to-node as well as master-to-node. I'll try the configuration tweaks suggested on the flannel ticket. I still don't know what kube-state-metrics could do to help the situation 😂
