### ISSUE TITLE
Errors when applying AuthorizationPolicy

### ISSUE THREAD

**Issue by jfassad** [istio/istio#24701]
**Bug description**

Applying any AuthorizationPolicy with action ALLOW generates errors in the istiod logs

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Applying a simple ALLOW policy shouldn't generate error logs

**Steps to reproduce the bug**

```
kubectl create ns test
kubectl label ns test istio-injection=enabled
kubectl -n test apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml


kubectl apply -f - << EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin-allow
  namespace: test
  labels:
    app: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - "/anything/test"
EOF
```

Errors observed in istiod logs

```
2020-06-16T11:10:59.728843Z     info    ads     LDS: PUSH for node:test.test listeners:55
2020-06-16T11:10:59.736691Z     info    ads     Pushing sidecar~172.25.101.224~httpbin-779c54bf49-9v78h.test~test.svc.cluster.local-777
2020-06-16T11:10:59.742458Z     error   status  Distribution Event Queue overwhelmed, status will be invalid.
2020-06-16T11:10:59.745035Z     error   authorization   skipped rule ns[test]-policy[httpbin-allow]-rule[0]: path-matcher must not be used in TCP
2020-06-16T11:10:59.748409Z     error   status  Distribution Event Queue overwhelmed, status will be invalid.
2020-06-16T11:10:59.758012Z     info    ads     LDS: PUSH for node:httpbin-779c54bf49-9v78h.test listeners:55
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (8 proxies)

$  kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

istio-operator controller

**Environment where bug was observed (cloud vendor, OS, etc)**

aws kops 1.17.0 - ubuntu 20.04

**Comment by rolandkool** [comment]
I'm seeing the same errors in the logs when applying AuthorizationPolicies.
To add to the description, the `path-matcher must not be used in TCP` part seems to refer to a TCP service. However, in our case, there is no TCP service in the namespace, only HTTP ones (considering the port naming convention in the `service` resource that all start with `http`).

**Comment by stewartbutler** [comment]
@howardjohn The Queue overwhelmed error seems suspicious, as does the authorization error. Have you seen this before?

**Comment by howardjohn** [comment]
`Distribution Event Queue overwhelmed, status will be invalid` is a bug that was fixed but is completely irrelevant to this

**Comment by yangminzhu** [comment]
Both HTTP and TCP config is generated in advance as a cache so that it could be reused in filter chain generation. You probably only have HTTP filter chain and the TCP one is never used, but the side effect is the error logging.

I think the logging can be improved to reduce the confusion here.

**Comment by jfassad** [comment]
Yeah I had something else misconfigured and this error led me to believe this was the problem... spent more time than I care to admit trying to fix it.

**Comment by iandyh** [comment]
@howardjohn I am still seeing the errors in istiod:1.6.3 though without applying any auth policies. Is this expected?

**Comment by yangminzhu** [comment]
@iandyh this is not fixed yet but you shouldn't see it if you do not have any auth policies, could you get a config dump of the policies applied and the istiod log?

**Comment by iandyh** [comment]
@yangminzhu Thanks for the reply.

> could you get a config dump of the policies (If that's what you are referring to)
```
kubectl get authorizationpolicies.security.istio.io -A
No resources found
```
> istiod log

```
2020-07-15T02:52:38.677877Z     error   status  Distribution Event Queue overwhelmed, status will be invalid.
2020-07-15T02:52:38.677886Z     error   status  Distribution Event Queue overwhelmed, status will be invalid.
```
I don't see other suspicious log entries around it.

**Comment by yangminzhu** [comment]
@iandyh I think that log is irrelevant to this and authz policy, see https://github.com/istio/istio/issues/24701#issuecomment-649678657

**Comment by iandyh** [comment]
@yangminzhu yes, what I want to say is after seeing the comment:

`I am still seeing the errors in istiod:1.6.3 though without applying any auth policies. Is this expected?`

So I think the bug has not been fixed yet.

**Comment by Jeskz0rd** [comment]
I can confirm the same (lots of) logs in 1.6.8.
> path-matcher must not be used in TCP

BTW, the Authz Policies are working pretty fine!

**Comment by yangminzhu** [comment]
@xulingqing has a PR to fix the logging which would be in 1.8 (it's a bit too late to get it to 1.7).

**Comment by Jeskz0rd** [comment]
Thanks for the update and MR @yangminzhu @xulingqing !  👍
