### ISSUE TITLE
Pods can't access external services when Istio is enabled

### ISSUE THREAD

**Issue by haimari** [istio/istio#26431]
I’m facing an issue with RKE + Istio on Bare metal.

After following Rancher [documentation](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/setup/enable-istio-in-cluster/), to enable istio and sidecar injection, 
`service` to `service` communication works ok inside the mesh.
However the pods can’t access any external services outside the cluster

(mongodb `TCP 27017`)
(voltdb `TCP 21212`)

I verified that:

`MeshConfig.OutboundTrafficPolicy.Mode` is set to `ALLOW_ANY` (this is the default)

```
kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: ALLOW_ANY" | uniq
mode: ALLOW_ANY
```

If i disable Istio and redeploy, pods are able to access external services normally.
Tried with Istio-cni 1.4 & 1.5

```
kubectl describe pod istio-policy-58c96755d9-7z5xd -n istio-system
Name:               istio-policy-58c96755d9-7z5xd
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               was-prd-k8s-worker3/X.X.X.X
Start Time:         Wed, 12 Aug 2020 20:55:17 +0300
Labels:             app=policy
                    chart=mixer
                    heritage=Tiller
                    istio=mixer
                    istio-mixer-type=policy
                    pod-template-hash=58c96755d9
                    release=cluster-istio
                    security.istio.io/tlsMode=istio
Annotations:        cni.projectcalico.org/podIP: 10.42.46.79/32
                    cni.projectcalico.org/podIPs: 10.42.46.79/32
                    sidecar.istio.io/inject: false
Status:             Running
IP:                 10.42.46.79
Controlled By:      ReplicaSet/istio-policy-58c96755d9
Containers:
  mixer:
    Container ID:  docker://ed0389efb2fa4d4e72327c6a187929690a63e4729b348734a08110b1c7ddf595
    Image:         rancher/istio-mixer:1.4.10
    Image ID:      docker-pullable://rancher/istio-mixer@sha256:621b0dacfcc28f96b8c76f8ccfe05335c8c9d31e080695331d8b145b36f9981e
    Ports:         15014/TCP, 42422/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --monitoringPort=15014
      --address
      unix:///sock/mixer.socket
      --log_output_level=default:info
      --configStoreURL=mcp://istio-galley.istio-system.svc:9901
      --configDefaultNamespace=istio-system
      --useAdapterCRDs=false
      --useTemplateCRDs=false
      --trace_zipkin_url=http://zipkin.istio-system:9411/api/v1/spans
    State:          Running
      Started:      Wed, 12 Aug 2020 20:55:58 +0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 12 Aug 2020 20:55:38 +0300
      Finished:     Wed, 12 Aug 2020 20:55:57 +0300
    Ready:          True
    Restart Count:  2
    Limits:
      cpu:     4800m
      memory:  4Gi
    Requests:
      cpu:     1
      memory:  1Gi
    Liveness:  http-get http://:15014/version delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      GOMAXPROCS:     6
    Mounts:
      /etc/certs from istio-certs (ro)
      /sock from uds-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-4w5z8 (ro)
  istio-proxy:
    Container ID:  docker://a857d110efb4d9d8f3651e2ad4e487c11d03ebf6bb9b93ac35ada82f97da991d
    Image:         rancher/istio-proxyv2:1.4.10
    Image ID:      docker-pullable://rancher/istio-proxyv2@sha256:3a5b00b8b2c663defbf1410040c063265e71fe4e1a08203d11938fbb51b325bf
    Ports:         9091/TCP, 15004/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      istio-policy
      --templateFile
      /etc/istio/proxy/envoy_policy.yaml.tmpl
      --controlPlaneAuthPolicy
      NONE
      --log_output_level=default:info
    State:          Running
      Started:      Wed, 12 Aug 2020 20:55:19 +0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAME:       istio-policy-58c96755d9-7z5xd (v1:metadata.name)
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      INSTANCE_IP:     (v1:status.podIP)
      SDS_ENABLED:    false
    Mounts:
      /etc/certs from istio-certs (ro)
      /sock from uds-socket (rw)
      /var/run/secrets/istio.io/policy/adapter from policy-adapter-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-4w5z8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-mixer-service-account
    Optional:    true
  uds-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  policy-adapter-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  policy-adapter-secret
    Optional:    true
  istio-mixer-service-account-token-4w5z8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-mixer-service-account-token-4w5z8
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
---
| Service | Version|
| :-- | :-- |
|Rancher |`v2.4.4` |
|Istio/istio-cni|`1.4.10` / `1.5`|
|K8S|`1.17.6`|

**Comment by howardjohn** [comment]
> However the pods can’t access any external services outside the cluster

Cannot access *any* or *some*? Can you give a specific request that is failnig and post a config dump? https://github.com/istio/istio/wiki/Troubleshooting-Istio

Btw https://istio.io/latest/news/support/announcing-1.4-eol-final/ since 1.4 we have fixed numerous issues in this area

**Comment by haimari** [comment]
Seems that some traffic does go out (HTTP) and some TCP didn't.

Created a new Bare metal cluster with 
rancher: 2.4.5
Docker 19.3.12
k8s 18.6 
Istio 1.4.10 / 1.5.8 

noticed this error with both versions:

```
2020-08-14T18:35:58.603158Z	error	Patch webhook failed: mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" not found
```

**Comment by haimari** [comment]
Hello,

I've set up a new Bare Metal RKE cluster, after deploying a new Rancher service on another dedicated RKE.
Deployed applications and verified they work as expected without Istio enables, using TCP dump i could see successful communication between the pod and the external mongodb server in TCP 27017.

Then enabled istio on the cluster using Rancher UI, enabled it on the namespace and redeployed the apps.
Tested HTTP requests to **external** service (curl http://ipinfo.io for example) and see that **HTTP works OK**

Then run TCP dump again from the pod and i see that there is **no data coming back** from the mongodb server (TCP 27017).

To debug i run the following:
```
kubectl -n prd exec -it data-api-prd-7b59b48cdd-cmclx -c data-api -- tcpdump -nnp port 27017 -w dump-no-istio.pcap
```
Then copied the pcap file and viewed in wireshark:

```
kubectl cp prd/data-api-prd-7b59b48cdd-cmclx:/app/dump-no-istio.pcap ./dump-no-istio.pcap
```

Did this twice (istio enabled/disabled)
I don't see any Reset or drops just what you see below.

While i cant display the content of the TCP stream here, i can display the packet flow.
In the stream i see mongodb data returned successfully, when istio disabled. (no label on naespace)

When istio disabled:

![image](https://user-images.githubusercontent.com/11332517/90560934-904de200-e1a8-11ea-9882-656208e80fff.png)

When istio enabled:

![image](https://user-images.githubusercontent.com/11332517/90561047-c4c19e00-e1a8-11ea-8bff-0815b315a0cb.png)


---
| Service | Version|
| :-- | :-- |
|Rancher |`v2.4.5` |
|Istio|`1.5.8`|
|K8S|`1.18.6`|
|Docker|`19.3.12`|

**Comment by haimari** [comment]
When testing directly from the pod with istio enabled, and connecting from CLI to the external mongodb server it works.
So i think this has to do with the application code, using a protocol which does not work correctly when istio is enabled

This is the application Error:

```
java.nio.channels.ClosedChannelException: null
	at shaded.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source)
{"service": "data-api", "level": "ERROR", "ts": "2020-08-19 13:59:10,905", "class": "reactivemongo.core.actors.MongoDBSystem", "line": "56", "message": "[Supervisor-3/Connection-4] Fails to connect channel #a67dfbfd"}
java.nio.channels.ClosedChannelException: null
```

**Comment by haimari** [comment]
While this is old (2018) 

As mentioned [here](https://istio.io/latest/blog/2018/egress-mongo/) this could be the issue 

> Note that the protocol TCP is specified instead of MONGO due to the fact that the traffic can be encrypted in case the MongoDB protocol runs on top of TLS. If the traffic is encrypted, the encrypted MongoDB protocol cannot be parsed by the Istio proxy.

Creating serviceEntry did not seem to solve the issue...
Can anyone advise on how to set this correctly when Istio is deployed via rancher ?

**Comment by haimari** [comment]
eventually found out that the issue was in application side (client)
We upgraded Reactive mongo to 20.11 and it works as expected (no SSL)
