### ISSUE TITLE
Istio mTLS strange behavior (bug?) 

### ISSUE THREAD

**Issue by m0ps** [istio/istio#26922]
**Bug description**
Currently, we are working on implementing a new GKE setup for our application. It includes GKE (1.16) with Workload Identity and Istio OSS (1.6.8). We are trying to apply the STRICT mTLS policy. And it works fine for most microservices except few ones that are calling another one during startup. It receives TCP RST. And it receives due that fact, that it tries to connect without mTLS (plain-text http):

`debug envoy connection [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C77289] TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST`

I thought that we affected that bug: https://github.com/istio/istio/issues/11130, but… it’s not true, because I’m able to do the same call via curl successfully (for test purposes, I’ve added curl command prior to java -jar app.jar in entrypoint). Moreover, in case I’m disabling STRICT mTLS mode during startup and re-add it (STRICT policy) after successful application initialization - it able to make the same call to the same destination microservice, which is totally weird.

Both microservices are Java11 springoot… ReactorNetty/0.9.5.RELEASE is used for making call.

We have old cluster (GKE 1.14 without workload identity) and Istio 1.1.17 and here it works fine.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.8
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
ilb-gateway version:
pilot version: 1.6.8
data plane version: 1.6.8 (103 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
With istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

**Comment by m0ps** [comment]
I’ve tried to look into **x_forwarded_client_cert** headers (an only successful connection is logged in envoy logs) and the picture is following:
`"x_forwarded_client_cert": "By=spiffe://cluster.local/ns/dst-qa/sa/iden-dst-qa-us-west1;Hash=2c63516e6f040e774e5d6b4ca42016f587dc831a3b59bcd031ae5661c00fb2b2;Subject="";URI=spiffe://cluster.local/ns/src-qa/sa/iden-src-qa-us-west1",`

The connection from another source pod to the same destination:

`"x_forwarded_client_cert": "By=spiffe://cluster.local/ns/dst-qa/sa/iden-dst-qa-us-west1;Hash=307a06d8fbbff3a23cce3fafa71890fdbb56e5557acdf64811b24916fe320956;Subject="";URI=spiffe://cluster.local/ns/src-dev/sa/iden-src-dev-us-west1",`

spiffe URI is the same, but hash is different, so I hope that there should not be an issue. Each connection uses it’s own certificates(?)

The most interesting thing is tcpdump output. During the failed connection, we have the following picture:
![96c072e92043f748d3b6613037172890c094420a](https://user-images.githubusercontent.com/5680580/91715647-ba36d980-eb96-11ea-8614-fd9778eea6d7.png)

So it sends packet 2 times. The problem is with packet num 2078… It sent as a plaint test, but the target expects mTLS. At the same time, we have packet num 2074 which I guess should be a valid one after which communication between pods should be established.

The situation with successful connection is also not so clear for me:
![6bef9ffea325403654a8816434ac294afc8a25c5](https://user-images.githubusercontent.com/5680580/91715678-d33f8a80-eb96-11ea-847f-6aaaad5ab4e3.png)

From my understanding - mTLS communication performed within 288-301 packets, but… why I can see plaintext response (packet num 302)?
P.S. http/400 is a valid response that I’m expecting as a result of my request.

**Comment by m0ps** [comment]
The issue is resolved now.
After examining of debug logs from caller pod, the following message was fond:

    [2020-09-11T17:50:48.061Z] "- - -" 0 - "-" "-" 402 0 3885 - "-" "-" "-" "-" "10.160.12.136:80" PassthroughCluster 10.160.162.112:46154 10.160.12.136:80 10.160.162.112:46146 - 

The key is **PassthroughCluster** . It means that the connection was not handled by any of envoy routes and handled by default PassthroughCluster virtual cluster.

Disabling of **PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND** solve the issue, but... a potential downside of this solution is that some of the telemetry metrics on the client side can be loosed.

More correct solution become increasing of **protocolDetectionTimeout** to 5s (default is 100ms). Now apps operate correctly in any phase.

Unfortunately, the root cause of such behavior is still not clear.

P.S. Solution was provided by GCP Support Team.

**Comment by m0ps** [comment]
It seems like this issue contains related info: https://github.com/istio/istio/issues/16581

**Comment by incfly** [comment]
For people who may potentially affected by this issue, this is caused by protocol detection timeout, and the envoy is then using passthrough cluster(which is plaintext) config to send request. Therefore strict mTLS server can't accept the request.

Add `PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND = true`

**Comment by jasonhao518** [comment]
quite strange, I faced the same issue, I'm using spring cloud gateway with latest reactor-netty version, and istio 1.14.  Even after applied the settings  PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND = false, the issue still there,  getting upstream connect error or disconnect/reset before headers. reset reason: connection failure error
