### ISSUE TITLE
VM mesh expansion, fails on restart

### ISSUE THREAD

**Issue by peter-fe** [istio/istio#27691]
**Bug description**
Extending the mesh by one VM, setup done accordingly to [1.7 manual](https://istio.io/latest/docs/setup/install/virtual-machine/)

Mesh gets extended, VM shows up with **istioctl proxy-status**, fine so far.

```
nexus.default                                          SYNCED     SYNCED     SYNCED     SYNCED     istiod-6674ccc856-gknmq     1.7.0
```

#### sidecar.env was adjusted to read/write the certificates from/to a non volatile file path.
```
PROV_CERT=/etc/certs
OUTPUT_CERTS=/etc/certs
```

After a VM restart, the istio-sidecar fails to start because it expects an istio-token in /var/run/secrets/tokens/istio-token, which is obviously not there because of the restart and the volatile behaviour of /var/run.
I'm really confused, why this token is needed, when the certificates are available under /etc/certs, I was assuming the short lived token is only needed for initializing and getting the first set of certificates.

```
2020-10-02T12:10:08.321391Z     error   sds     Failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory
2020-10-02T12:10:08.321453Z     info    sds     resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
2020-10-02T12:10:30.771677Z     info    sds     resource:default new connection
2020-10-02T12:10:30.771737Z     error   sds     failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory from path ./var/run/secrets/tokens/istio-token
2020-10-02T12:10:30.771744Z     error   sds     Failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory
2020-10-02T12:10:30.771800Z     info    sds     resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
2020-10-02T12:10:32.459164Z     info    sds     resource:default new connection
2020-10-02T12:10:32.459222Z     error   sds     failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory from path ./var/run/secrets/tokens/istio-token
2020-10-02T12:10:32.459228Z     error   sds     Failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory
2020-10-02T12:10:32.459308Z     info    sds     resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
2020-10-02T12:11:01.539130Z     info    sds     resource:default new connection
2020-10-02T12:11:01.539203Z     error   sds     failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory from path ./var/run/secrets/tokens/istio-token
2020-10-02T12:11:01.539211Z     error   sds     Failed to get credential token: open ./var/run/secrets/tokens/istio-token: no such file or directory
2020-10-02T12:11:01.539275Z     info    sds     resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
```

In which real world setup you can expect a VM to not get restarted?
If the token is always needed I don't understand what the certificates are good for (except the root one)
What happens, without restart, but after the token has expired when it is constantly used?

[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
If valid certificates are existing in OUTPUT_CERTS or PROV_CERT they should get precedence and no token is needed.
If only the root cert is there, the short lived token is needed to seed the OUTPUT_CERTS with newly fetched certificates.

**Steps to reproduce the bug**
Restart a VM that is part of the mesh.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.0 (1 proxies), 1.7.3 (4 proxies)

Client Version: v1.19.2
Server Version: v1.16.13-gke.401
```

**How was Istio installed?**
```
istioctl install -f values.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
```
GCE, GKE
```

**Comment by howardjohn** [comment]
@williamaronli

**Comment by peter-fe** [comment]
Some additional info:

When you already have valid certificates in a non volatile storage path and you do a restart, you get that already mentioned error that there is not token in /var/run/secrets/tokens/istio-token.
When you do a simple touch /var/run/secrets/tokens/istio-token you can start the sidecar again.
=> Seems that there is a check just for file existence that should not take place if certs are found/valid

It's very hard to get that whole process running, following examples all lead to a non functioning deployment:

OUTPUT_CERTS & PROV_CERT set to /etc/certs, root-cert.pem placed in /etc/certs, token placed in /var/run/secrets/tokens
=> start fails, complains a missing cert-chain.pem in /etc/certs
=> seems like if the root-cert.pem is found, a cert-chain.pem and a key.pem is assumed to exist as well, no token auth is done to get the certificates.

Also it seems if the process was running through once, I was not able to force a new token auth
=> I cleared the certs (except the root-cert.pem) provided a fresh token and started the sidecar.
=> startup fails because of missing cert-chain.pem, token gets ignored, is there some logic in place, if initialized once the token flow gets ignored completely?  (like a cache)

Expected functionality:

OUTPUT_CERTS or PROV_CERT have valid certificates in place => no token is needed => sidecar starts up and places new certs in OUTPUT_CERTS.

OUTPUT_CERTS or PROV_CERT only holding the root-cert.pem => a valid token is needed => sidecar starts up and places new certs in OUTPUT_CERTS.

The permissions of the created certificates should comply to a best practice minimum, currently the permissions of the created certificates seem way to high.

**Comment by peter-fe** [comment]
Was that issue addressed in some way?

**Comment by howardjohn** [comment]
I believe this will be fixed by https://github.com/istio/istio/pull/29688, I will make sure we add an explicit test case

**Comment by peter-fe** [comment]
@howardjohn, that sounds great! Especially adding those tests would be a great deal stabilizing that VM mesh expansion area.

**Comment by howardjohn** [comment]
It actually wasn't fixed, but i have added 9fbcd981c87bd5d30e22769b2de5eaf4de035824 to that PR and tested it. Thanks for the report!
