### ISSUE TITLE
TestVMRegistrationLifecycle test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29100]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29023/integ-pilot-k8s-tests_istio/1329867882519072768

**Comment by howardjohn** [comment]
I have been watching flakes pretty close and have only seen this 2x I think, so seems pretty rare

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1333462313176403968

**Comment by stevenctl** [comment]
For the issue with `deletes WorkloadEntry` the test should wait for at least 2 * the grace period. 
For the issue with `reuses WorkloadEntry` initial registration issues/delays may be causing this. The way the test is written doesn't include `checkOK` – the WorkloadEntry might not exist at all because of issues with the first part of the test. 

Both of these should be fixed by https://github.com/istio/istio/pull/29130

**Comment by stevenctl** [comment]
I don't think I've seen this flake for a few weeks now.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1358811676220067840

seems pretty rare but still happening
