### ISSUE TITLE
DestinationRule merging not working after upgrading from v. 1.13.2 to 1.14.3

### ISSUE THREAD

**Issue by JesperBerggren** [istio/istio#40952]
### Bug Description

We've just upgraded from version 1.13.2 to 1.14.3.

Up until now we've had merging of DestinationRules working flawlessly.

Our scenario for this is that we're using the Istio ingress gateway as an integration layer to ensure security, logging etc. for backend systems (outside Kubernetes) to call an external API.
Depending on what endpoint is called on the Istio gateway we're using different subsets to call the external API with different client certificates.

E.g. (simplified for readability):
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: solution-ingress-gateway-mtls
  namespace: solution
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    tls:
      mode: MUTUAL
      minProtocolVersion: TLSV1_2
      credentialName: solution-certs-ingress-mtls
    hosts:
    - solution.servicemesh.dev.company.local
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: digitalpost-digst
  namespace: digitalpost-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: digitalpost-digst
  namespace: digitalpost-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/afu/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-afu
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/udk/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-udk
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-afu
    trafficPolicy:
      loadBalancer:
        simple: LEAST_REQUEST
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-afu-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-udk
    trafficPolicy:
      loadBalancer:
        simple: LEAST_REQUEST
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-udk-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
```
As you can see there are two different subsets defined in two separate namespaces but exported to the istio-system namespace.

In Istio v. 1.13.2 the configuration was interpreted like this:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-6779c46896-655qc
SERVICE FQDN                                                                           PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                                       -         -                               -             STATIC         
agent                                                                                  -         -                               -             STATIC         
api.test.solution.dk                                                                   443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
api.test.solution.dk                                                                   443       solution-digst-aes              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-aes
api.test.solution.dk                                                                   443       solution-digst-udk              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
```
In Istion v. 1.14.3 the configuration is like this:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-79f6886b46-8xmtm
SERVICE FQDN                                                                           PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                                       -         -                               -             STATIC         
agent                                                                                  -         -                               -             STATIC         
api.test.solution.dk                                                                   443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
api.test.solution.dk                                                                   443       solution-digst-aes              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-aes
```
Notice that it now only knows the first subset!?

I found this issue: https://github.com/istio/istio/issues/22997 but switching to the Kubernetes gateway-api seems like a huge step. 
I also found this in the release notes for v. 1.14: 

> Fixed the problem that xDS may not be updated if multiple destinationRules for a service are merged. In this case the merged rule only records one name/namespace pair of all the destinationRules. However, this meta is used to record config dependencies of a sidecar.

> In this fix, we introduce a new struct consolidatedDestRule and record all the destinationrules’ meta to avoid missing any destinationRule dependencies. ([Issue #38082](https://github.com/istio/istio/issues/38082))

Can anybody give some insights on why the merging no longer works?

Best regards
Jesper Berggren

### Version

```prose
$ istioctl version
client version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3 (31 proxies)
```

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I will take a look

**Comment by hzxuzhonghu** [comment]
In both 1.13 and 1.16, i only get the 
```
root@opensrc:~# istioctl pc cluster istio-ingressgateway-57dd48786c-dwmj9 -n istio-system |grep api.test.solution.dk
api.test.solution.dk                                                  443       -          outbound      STRICT_DNS 
```

**Comment by hzxuzhonghu** [comment]
Added tests for this in https://github.com/istio/istio/pull/40980

**Comment by JesperBerggren** [comment]
I wonder if I simplified the yaml too much. I'll try to redeploy it in a clean cluster.
I'll get back later.
//Jesper

**Comment by JesperBerggren** [comment]
Hey again,

I've made the yaml configuration complete and easily deployable on both Istio v. 1.13.2 and 1.14.3.
This is it:
```
kind: Namespace
apiVersion: v1
metadata:
  name: solution-afu
  labels:
    name: solution-afu
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: solution-udk
  labels:
    name: solution-udk
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: solution
  labels:
    name: solution
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: solution-ingress-gateway-mtls
  namespace: solution
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    tls:
      mode: MUTUAL
      minProtocolVersion: TLSV1_2
      credentialName: solution-certs-ingress-mtls
    hosts:
    - solution.servicemesh.dev.company.local
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: solution-digst
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: solution-digst
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/afu/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-afu
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/udk/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-udk
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-afu
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-afu-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-udk
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-udk-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
```

On v. 1.13.2 it gives me this configuration of the ingressgateway:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-f589d66b6-q8k7f
SERVICE FQDN                                                      PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                  -         -                               -             STATIC         
agent                                                             -         -                               -             STATIC         
api.test.solution.dk                                              443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
api.test.solution.dk                                              443       solution-digst-afu              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
api.test.solution.dk                                              443       solution-digst-udk              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
```

On v. 1.14.3 it gives me this configuration of the ingressgateway:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-7b4969b798-7qd5d
SERVICE FQDN                                                      PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                  -         -                               -             STATIC         
agent                                                             -         -                               -             STATIC         
api.test.solution.dk                                              443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
api.test.solution.dk                                              443       solution-digst-afu              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
```

I does indeed work on 1.13.2 but no longer on 1.14.3.

I should mention that I deploy the yaml file on 1.13.2 and afterwards _upgrades_ Istio after which it no longer works.

Furthermore I've installed Istio with the following options (among many other but these seem relevant to mention):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    enableAutoMtls: true
    defaultServiceExportTo: ["."]
    defaultVirtualServiceExportTo: ["."]
    defaultDestinationRuleExportTo: ["."]
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
```

Best regards
Jesper Berggren

**Comment by JesperBerggren** [comment]
Just for good measure I applied the yaml configuration on a completely fresh Istio installation running v. 1.14.3 and it still doesn't show both subsets.
// Jesper

**Comment by hzxuzhonghu** [comment]
thanks, i can  reproduce with  latest yaml

**Comment by hzxuzhonghu** [comment]
I suspect we merge service differently in 1.13 and 1.14, not related to Dr merge.  That's why https://github.com/istio/istio/pull/40980 behave same in both releases

**Comment by hzxuzhonghu** [comment]
Figured out the root cause is https://github.com/istio/istio/pull/37413, before that it works, I do not analyzing why, since it is a little old.

But i do not know how to fix it or whether we should fix it.

There are two services defined by 2 serviceentries with different namespaces. During  SidecarScope building. there are many places we use svc hostname as a key for servcieMap. 

So actually for `api.test.solution.dk`, we will only cache the older one service. So when we get destinationRule for ingress-gateway, we only get one from [proxy namespace, svc namespace, or global dr], we can not get the dr from the second service ns, which is none of the above.

**Comment by howardjohn** [comment]
The intent is that if users have multiple they should pick one with Sidecar scope; if they don't we pick an arbitrary one. So within SidecarScope there is always 1 unique hostname; outside of sidecarscope we need hostname+namespace as pair.

So maybe we are inconsistently picking which one?

**Comment by hzxuzhonghu** [comment]
Yup, definitely there are inconsistencies.  Need a thorough and close look.

**Comment by JesperBerggren** [comment]
I'll be away from the computer for the next 8 days.
Please don't close this issue meanwhile - unless you've fixed it :)

**Comment by hzxuzhonghu** [comment]
Sure

**Comment by JesperBerggren** [comment]
Hi, what's the status on this issue?
Reading up on the status of the pull request it's not an easy fix.

In the meantime we're stuck on version 13.8, which sooner og later will become a problem.

Thanks for looking into the matter though :-)

**Comment by hzxuzhonghu** [comment]
@howardjohn What is the conclusion from WG meeting?

**Comment by howardjohn** [comment]
Its discussed in https://docs.google.com/document/d/1wsa06GGiq1LEGwhkiPP0FKIZJqdAiue-VeBonWAzAyk/edit as bit. But basically, there was desire to not merge https://github.com/istio/istio/pull/41062 due to the reasons mentioned in the PR. Instead, we should fix the underlying issue without changing the SidecarScope semantics, even if that means reverting the original PR that caused the regrssion.

**Comment by hzxuzhonghu** [comment]
Thanks

**Comment by JesperBerggren** [comment]
Hi @howardjohn and @hzxuzhonghu 

Can you please give me a status of this issue?

It has become a problem for us because we're still stuck on version 1.13. 
We're no longer getting security patches for Istio and furthermore we're stuck on Kubernetes version 1.23.

Being one of Europe’s largest pension funds that have just started it's journey towards a service mesh architecture based on Istio, this issue is causing some problems in-house and a few has even started to raise questions about the validity of the product choice.

Is there something we can do to assist you in fixing the issue?
And what timeline do you think we are looking into?

Thanks in advance for an answer.

Best regards
Jesper Berggren

**Comment by pantianying** [comment]
Is this still an issue?

**Comment by hzxuzhonghu** [comment]
Still exist, see https://github.com/istio/istio/issues/48169

**Comment by jwendell** [comment]
@hzxuzhonghu is this also fixed by https://github.com/istio/istio/pull/48896 ?

**Comment by hzxuzhonghu** [comment]
Yes, @jwendell
