### ISSUE TITLE
TestCheckCache failing daily-release/489/daily-e2e-cluster_wide-auth

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#4595]
[prow build log e2e-cluster_wide-auth](https://storage.googleapis.com/istio-prow/pull/istio-releases_daily-release/489/daily-e2e-cluster_wide-auth/424/build-log.txt)

I grepped for "FAIL: TestCheckCache" to try to find errors within this case and haven't found anything yet

**Comment by douglas-reid** [comment]
cc: @bianpengyuan, who I believe is already investigating.

```
I0328 14:44:17.853] --- FAIL: TestCheckCache (36.37s)
I0328 14:44:17.853] 	mixer_test.go:532: Query prometheus to get baseline cache hits...
I0328 14:44:17.853] 	mixer_test.go:538: Baseline cache hits: 3
I0328 14:44:17.853] 	mixer_test.go:539: Start to call visit function for 2 times...
I0328 14:44:17.853] 	mixer_test.go:548: Query promethus to get new cache hits number...
I0328 14:44:17.853] 	mixer_test.go:554: New cache hits: 3
I0328 14:44:17.853] 	mixer_test.go:264: Check cache hit: 0 is less than expected: 1
```

**Comment by bianpengyuan** [comment]
This should already be fixed by #4495 and the log seems out of date. @cmluciano When was this failure happens?

**Comment by cmluciano** [comment]
That log is from a build earlier today https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/489/daily-e2e-cluster_wide-auth/424/

**Comment by bianpengyuan** [comment]
I am not sure why prow is not testing with the newest code... The PR was merged two days ago. @cmluciano Any idea about this?

**Comment by cmluciano** [comment]
Seems to still be flaking here http://k8s-testgrid.appspot.com/istio#daily-e2e-cluster_wide-auth .

Not sure if @sebastienvas or @hklai have more input on daily builds

**Comment by hklai** [comment]
It still happened today.
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio-releases_daily-release/493/daily-e2e-rbac-no_auth/461

PTAL as soon as possible as it is blocking daily releases, which we have not had any for a few days due to both test failures and pipeline problem.

/cc @wattli

**Comment by bianpengyuan** [comment]
@hklai The test was still using the stale version of mixer_e2e which does not include #4495. Do you have idea why prow does not test with the newest code?
